decompiler: XmlDecode Class Reference
XmlDecode Class Reference
An XML based decoder.
#include <marshal.hh>
Public Member Functions
XmlDecode (const AddrSpaceManager *spc, const Element *root)
Constructor with preparsed root.
XmlDecode (const AddrSpaceManager *spc)
Constructor for use with ingestStream.
const Element * getCurrentXmlElement (void) const
Get pointer to underlying XML element object.
virtual void ingestStream (istream &s)
Prepare to decode a given stream.
virtual uint4 peekElement (void)
Peek at the next child element of the current parent, without traversing in (opening) it.
virtual uint4 openElement (void)
Open (traverse into) the next child element of the current parent.
virtual uint4 openElement (const ElementId &elemId)
Open (traverse into) the next child element, which must be of a specific type.
virtual void closeElement (uint4 id)
Close the current element.
virtual void closeElementSkipping (uint4 id)
Close the current element, skipping any child elements that have not yet been parsed.
virtual void rewindAttributes (void)
Reset attribute traversal for the current element.
virtual uint4 getNextAttributeId (void)
Get the next attribute id for the current element.
virtual bool readBool (void)
Parse the current attribute as a boolean value.
virtual bool readBool (const AttributeId &attribId)
Find and parse a specific attribute in the current element as a boolean value.
virtual intb readSignedInteger (void)
Parse the current attribute as a signed integer value.
virtual intb readSignedInteger (const AttributeId &attribId)
Find and parse a specific attribute in the current element as a signed integer.
virtual intb readSignedIntegerExpectString (const string &expect, intb expectval)
Parse the current attribute as either a signed integer value or a string.
virtual intb readSignedIntegerExpectString (const AttributeId &attribId, const string &expect, intb expectval)
Find and parse a specific attribute in the current element as either a signed integer or a string.
virtual uintb readUnsignedInteger (void)
Parse the current attribute as an unsigned integer value.
virtual uintb readUnsignedInteger (const AttributeId &attribId)
Find and parse a specific attribute in the current element as an unsigned integer.
virtual string readString (void)
Parse the current attribute as a string.
virtual string readString (const AttributeId &attribId)
Find the specific attribute in the current element and return it as a string.
virtual AddrSpace * readSpace (void)
Parse the current attribute as an address space.
virtual AddrSpace * readSpace (const AttributeId &attribId)
Find the specific attribute in the current element and return it as an address space.
Public Member Functions inherited from Decoder
Decoder (const AddrSpaceManager *spc)
Base constructor.
const AddrSpaceManager * getAddrSpaceManager (void) const
Get the manager used for address space decoding.
virtual ~Decoder (void)
Destructor.
void skipElement (void)
Skip parsing of the next element.
Private Member Functions
int4 findMatchingAttribute (const Element *el, const string &attribName)
Find the attribute index, within the given element, for the given name.
Private Attributes
Document * document
An ingested XML document, owned by this decoder.
const Element * rootElement
The root XML element to be decoded.
vector< const Element * > elStack
Stack of currently open elements.
vector< List::const_iterator > iterStack
Index of next child for each open element.
int4 attributeIndex
Position of current attribute to parse (in current element)
Additional Inherited Members
Protected Attributes inherited from Decoder
const AddrSpaceManager * spcManager
Manager for decoding address space attributes.
Detailed Description
An XML based decoder.
The underlying transfer encoding is an XML document. The decoder can either be initialized with an existing Element as the root of the data to transfer, or the ingestStream() method can be invoked to read the XML document from an input stream, in which case the decoder manages the Document object.
Member Function Documentation
void XmlDecode::closeElement (uint4 id) virtual
Close the current element.
The data for the current element is considered fully processed. If the element has additional children, an exception is thrown. The stream must indicate the end of the element in some way.
Parameters
id is the id of the element to close (which must be the current element)
Implements Decoder.
References attributeIndex, elStack, ElementId::find(), Element::getChildren(), Element::getName(), and iterStack.
void XmlDecode::closeElementSkipping (uint4 id) virtual
Close the current element, skipping any child elements that have not yet been parsed.
This closes the given element, which must be current. If there are child elements that have not been parsed, this is not considered an error, and they are skipped over in the parse.
Parameters
id is the id of the element to close (which must be the current element)
Implements Decoder.
References attributeIndex, elStack, ElementId::find(), Element::getName(), and iterStack.
int4 XmlDecode::findMatchingAttribute (const Element * el, const string & attribName) private
Find the attribute index, within the given element, for the given name.
Run through the attributes of the element until we find the one matching the name, or throw an exception otherwise.
Parameters
el is the given element to search
attribName is the attribute name to search for
Returns
the matching attribute index
References Element::getAttributeName(), and Element::getNumAttributes().
Referenced by readBool(), readSignedInteger(), readSpace(), readString(), and readUnsignedInteger().
uint4 XmlDecode::getNextAttributeId (void) virtual
Get the next attribute id for the current element.
Attributes are automatically set up for traversal using this method, when the element is opened. If all attributes have been traversed (or there are no attributes), 0 is returned.
Returns
the id of the next attribute or 0
Implements Decoder.
References attributeIndex, elStack, AttributeId::find(), and Element::getAttributeName().
void XmlDecode::ingestStream (istream & s) virtual
Prepare to decode a given stream.
Called once before any decoding. Currently this is assumed to make an internal copy of the stream data, i.e. the input stream is cleared before any decoding takes place.
Parameters
s is the given input stream to be decode
Returns
true if the stream was fully ingested
Implements Decoder.
References document, Document::getRoot(), rootElement, and xml_tree().
uint4 XmlDecode::openElement (void) virtual
Open (traverse into) the next child element of the current parent.
The child becomes the current parent. The list of attributes is initialized for use with getNextAttributeId.
Returns
the id of the child element
Implements Decoder.
References attributeIndex, elStack, ElementId::find(), Element::getChildren(), Element::getName(), iterStack, and rootElement.
uint4 XmlDecode::openElement (const ElementId & elemId) virtual
Open (traverse into) the next child element, which must be of a specific type.
The child becomes the current parent, and its attributes are initialized for use with getNextAttributeId. The child must match the given element id or an exception is thrown.
Parameters
elemId is the given element id to match
Returns
the id of the child element
Implements Decoder.
References attributeIndex, elStack, Element::getChildren(), ElementId::getId(), ElementId::getName(), Element::getName(), iterStack, and rootElement.
uint4 XmlDecode::peekElement (void) virtual
Peek at the next child element of the current parent, without traversing in (opening) it.
The element id is returned, which can be compared to ElementId labels. If there are no remaining child elements to traverse, 0 is returned.
Returns
the element id or 0
Implements Decoder.
References elStack, ElementId::find(), Element::getChildren(), Element::getName(), iterStack, and rootElement.
bool XmlDecode::readBool (void) virtual
Parse the current attribute as a boolean value.
The last attribute, as returned by getNextAttributeId, is treated as a boolean, and its value is returned.
Returns
the boolean value associated with the current attribute.
Implements Decoder.
References attributeIndex, elStack, Element::getAttributeValue(), and xml_readbool().
bool XmlDecode::readBool (const AttributeId & attribId) virtual
Find and parse a specific attribute in the current element as a boolean value.
The set of attributes for the current element is searched for a match to the given attribute id. This attribute is then parsed as a boolean and its value returned. If there is no attribute matching the id, an exception is thrown. Parsing via getNextAttributeId is reset.
Parameters
attribId is the specific attribute id to match
Returns
the boolean value
Implements Decoder.
References elStack, findMatchingAttribute(), Element::getAttributeValue(), Element::getContent(), AttributeId::getName(), and xml_readbool().
intb XmlDecode::readSignedInteger (void) virtual
Parse the current attribute as a signed integer value.
The last attribute, as returned by getNextAttributeId, is treated as a signed integer, and its value is returned.
Returns
the signed integer value associated with the current attribute.
Implements Decoder.
References attributeIndex, elStack, and Element::getAttributeValue().
intb XmlDecode::readSignedInteger (const AttributeId & attribId) virtual
Find and parse a specific attribute in the current element as a signed integer.
The set of attributes for the current element is searched for a match to the given attribute id. This attribute is then parsed as a signed integer and its value returned. If there is no attribute matching the id, an exception is thrown. Parsing via getNextAttributeId is reset.
Parameters
attribId is the specific attribute id to match
Returns
the signed integer value
Implements Decoder.
References elStack, findMatchingAttribute(), Element::getAttributeValue(), Element::getContent(), and AttributeId::getName().
intb XmlDecode::readSignedIntegerExpectString (const string & expect, intb expectval) virtual
Parse the current attribute as either a signed integer value or a string.
If the attribute is an integer, its value is returned. If the attribute is a string, it must match an expected string passed to the method, and a predetermined integer value associated with the string is returned. If the attribute neither matches the expected string nor is an integer, the return value is undefined.
Parameters
expect is the string value to expect if the attribute is encoded as a string
expectval is the integer value to return if the attribute matches the expected string
Returns
the encoded integer or the integer value associated with the expected string
Implements Decoder.
References attributeIndex, elStack, and Element::getAttributeValue().
intb XmlDecode::readSignedIntegerExpectString (const AttributeId & attribId, const string & expect, intb expectval) virtual
Find and parse a specific attribute in the current element as either a signed integer or a string.
If the attribute is an integer, its value is parsed and returned. If the attribute is encoded as a string, it must match an expected string passed to this method. In this case, a predetermined integer value is passed back, indicating a matching string was parsed. If the attribute neither matches the expected string nor is an integer, the return value is undefined. If there is no attribute matching the id, an exception is thrown.
Parameters
attribId is the specific attribute id to match
expect is the string to expect, if the attribute is not encoded as an integer
expectval is the integer value to return if the attribute matches the expected string
Returns
the encoded integer or the integer value associated with the expected string
Implements Decoder.
References readString().
AddrSpace * XmlDecode::readSpace (void) virtual
Parse the current attribute as an address space.
The last attribute, as returned by getNextAttributeId, is returned as an address space.
Returns
the address space associated with the current attribute.
Implements Decoder.
References attributeIndex, elStack, Element::getAttributeValue(), AddrSpaceManager::getSpaceByName(), and Decoder::spcManager.
AddrSpace * XmlDecode::readSpace (const AttributeId & attribId) virtual
Find the specific attribute in the current element and return it as an address space.
Search attributes from the current element for a match to the given attribute id. Return this attribute as an address space. If there is no attribute matching the id, an exception is thrown. Parse via getNextAttributeId is reset.
Parameters
attribId is the specific attribute id to match
Returns
the address space associated with the attribute
Implements Decoder.
References elStack, findMatchingAttribute(), Element::getAttributeValue(), Element::getContent(), AttributeId::getName(), AddrSpaceManager::getSpaceByName(), and Decoder::spcManager.
string XmlDecode::readString (void) virtual
Parse the current attribute as a string.
The last attribute, as returned by getNextAttributeId, is returned as a string.
Returns
the string associated with the current attribute.
Implements Decoder.
References attributeIndex, elStack, and Element::getAttributeValue().
Referenced by readSignedIntegerExpectString().
string XmlDecode::readString (const AttributeId & attribId) virtual
Find the specific attribute in the current element and return it as a string.
The set of attributes for the current element is searched for a match to the given attribute id. This attribute is then returned as a string. If there is no attribute matching the id, and exception is thrown. Parse via getNextAttributeId is reset.
Parameters
attribId is the specific attribute id to match
Returns
the string associated with the attribute
Implements Decoder.
References elStack, findMatchingAttribute(), Element::getAttributeValue(), Element::getContent(), and AttributeId::getName().
uintb XmlDecode::readUnsignedInteger (void) virtual
Parse the current attribute as an unsigned integer value.
The last attribute, as returned by getNextAttributeId, is treated as an unsigned integer, and its value is returned.
Returns
the unsigned integer value associated with the current attribute.
Implements Decoder.
References attributeIndex, elStack, and Element::getAttributeValue().
uintb XmlDecode::readUnsignedInteger (const AttributeId & attribId) virtual
Find and parse a specific attribute in the current element as an unsigned integer.
The set of attributes for the current element is searched for a match to the given attribute id. This attribute is then parsed as an unsigned integer and its value returned. If there is no attribute matching the id, an exception is thrown. Parsing via getNextAttributeId is reset.
Parameters
attribId is the specific attribute id to match
Returns
the unsigned integer value
Implements Decoder.
References elStack, findMatchingAttribute(), Element::getAttributeValue(), Element::getContent(), and AttributeId::getName().
void XmlDecode::rewindAttributes (void) virtual
Reset attribute traversal for the current element.
Attributes for a single element can be traversed more than once using the getNextAttributeId method.
Implements Decoder.
References attributeIndex.
The documentation for this class was generated from the following files:
marshal.hh
marshal.cc