decompiler: ContextInternal Class Reference
ContextInternal Class Reference
An in-memory implementation of the ContextDatabase interface.
#include <globalcontext.hh>
Classes
struct FreeArray
A context blob, holding context values across some range of code addresses.
Public Member Functions
virtual int4 getContextSize (void) const
Retrieve the number of words (uintm) in a context blob.
virtual void registerVariable (const string &nm, int4 sbit, int4 ebit)
Register a new named context variable (as a bit range) with the database.
virtual const uintm * getContext (const Address &addr) const
Get the context blob of values associated with a given address.
virtual const uintm * getContext (const Address &addr, uintb &first, uintb &last) const
Get the context blob of values associated with a given address and its bounding offsets.
virtual TrackedSet & getTrackedDefault (void)
Get the set of default values for all tracked registers.
virtual const TrackedSet & getTrackedSet (const Address &addr) const
Get the set of tracked register values associated with the given address.
virtual TrackedSet & createSet (const Address &addr1, const Address &addr2)
Create a tracked register set that is valid over the given range.
virtual void encode (Encoder &encoder) const
Encode the entire database to a stream.
virtual void decode (Decoder &decoder)
Restore the state of this database object from the given stream decoder.
virtual void decodeFromSpec (Decoder &decoder)
Add initial context state from elements in the compiler/processor specifications.
Public Member Functions inherited from ContextDatabase
virtual ~ContextDatabase ()
Destructor.
void setVariableDefault (const string &nm, uintm val)
Provide a default value for a context variable.
uintm getDefaultValue (const string &nm) const
Retrieve the default value for a context variable.
void setVariable (const string &nm, const Address &addr, uintm value)
Set a context value at the given address.
uintm getVariable (const string &nm, const Address &addr) const
Retrieve a context value at the given address.
void setContextChangePoint (const Address &addr, int4 num, uintm mask, uintm value)
Set a specific context value starting at the given address.
void setContextRegion (const Address &addr1, const Address &addr2, int4 num, uintm mask, uintm value)
Set a context variable value over a given range of addresses.
void setVariableRegion (const string &nm, const Address &begad, const Address &endad, uintm value)
Set a context variable by name over a given range of addresses.
uintb getTrackedValue (const VarnodeData &mem, const Address &point) const
Get the value of a tracked register at a specific address.
Private Member Functions
void encodeContext (Encoder &encoder, const Address &addr, const uintm *vec) const
Encode a single context block to a stream.
void decodeContext (Decoder &decoder, const Address &addr1, const Address &addr2)
Restore a context blob for given address range from a stream decoder.
virtual ContextBitRange & getVariable (const string &nm)
Retrieve the context variable description object by name.
virtual const ContextBitRange & getVariable (const string &nm) const
Retrieve the context variable description object by name.
virtual void getRegionForSet (vector< uintm * > &res, const Address &addr1, const Address &addr2, int4 num, uintm mask)
Grab the context blob(s) for the given address range, marking bits that will be set.
virtual void getRegionToChangePoint (vector< uintm * > &res, const Address &addr, int4 num, uintm mask)
Grab the context blob(s) starting at the given address up to the first point of change.
virtual uintm * getDefaultValue (void)
Retrieve the memory region holding all default context values.
virtual const uintm * getDefaultValue (void) const
Retrieve the memory region holding all default context values.
Private Attributes
int4 size
Number of words in a context blob (for this architecture)
map< string, ContextBitRange > variables
Map from context variable name to description object.
partmap< Address, FreeArray > database
Partition map of context blobs (FreeArray)
partmap< Address, TrackedSet > trackbase
Partition map of tracked register sets.
Additional Inherited Members
Static Protected Member Functions inherited from ContextDatabase
static void encodeTracked (Encoder &encoder, const Address &addr, const TrackedSet &vec)
Encode all tracked register values for a specific address to a stream.
static void decodeTracked (Decoder &decoder, TrackedSet &vec)
Restore a sequence of tracked register values from the given stream decoder.
Detailed Description
An in-memory implementation of the ContextDatabase interface.
Context blobs are held in a partition map on addresses. Any address within the map indicates a split point, where the value of a context variable was explicitly changed. Sets of tracked registers are held in a separate partition map.
Member Function Documentation
TrackedSet & ContextInternal::createSet (const Address & addr1, const Address & addr2) virtual
Create a tracked register set that is valid over the given range.
This really should be an internal routine. The created set is empty, old values are blown away. If old/default values are to be preserved, they must be copied back in.
Parameters
addr1 is the starting address of the given range
addr2 is (1 past) the ending address of the given range
Returns
the empty set of tracked register values
Implements ContextDatabase.
References partmap< _linetype, _valuetype >::clearRange(), and trackbase.
Referenced by decodeFromSpec().
void ContextInternal::decode (Decoder & decoder) virtual
Restore the state of this database object from the given stream decoder.
Parameters
decoder is the given stream decoder
Implements ContextDatabase.
References Decoder::closeElement(), decodeContext(), VarnodeData::decodeFromAttributes(), ContextDatabase::decodeTracked(), VarnodeData::getAddr(), Decoder::getNextAttributeId(), Decoder::openElement(), Decoder::rewindAttributes(), partmap< _linetype, _valuetype >::split(), and trackbase.
void ContextInternal::decodeContext (Decoder & decoder, const Address & addr1, const Address & addr2) private
Restore a context blob for given address range from a stream decoder.
Parse either a <context_pointset> or <context_set> element. In either case, children are parsed to get context variable values. Then a context blob is reconstructed from the values. The new blob is added to the interval map based on the address range. If the start address is invalid, the default value of the context variables are painted. The second address can be invalid, if only a split point is known.
Parameters
decoder is the stream decoder
addr1 is the starting address of the given range
addr2 is the ending address of the given range
References Decoder::closeElement(), getDefaultValue(), ContextBitRange::getMask(), getRegionForSet(), ContextBitRange::getShift(), getVariable(), ContextBitRange::getWord(), Address::isInvalid(), Decoder::openElement(), Decoder::readString(), Decoder::readUnsignedInteger(), ContextBitRange::setValue(), and size.
Referenced by decode(), and decodeFromSpec().
void ContextInternal::decodeFromSpec (Decoder & decoder) virtual
Add initial context state from elements in the compiler/processor specifications.
Parse a <context_data> element from the given stream decoder from either the compiler or processor specification file for the architecture, initializing this database.
Parameters
decoder is the given stream decoder
Implements ContextDatabase.
References Decoder::closeElement(), createSet(), decodeContext(), Range::decodeFromAttributes(), ContextDatabase::decodeTracked(), Decoder::getAddrSpaceManager(), Range::getFirstAddr(), Range::getLastAddrOpen(), and Decoder::openElement().
void ContextInternal::encode (Encoder & encoder) const virtual
Encode the entire database to a stream.
Parameters
encoder is the stream encoder
Implements ContextDatabase.
References partmap< _linetype, _valuetype >::begin(), Encoder::closeElement(), database, partmap< _linetype, _valuetype >::empty(), encodeContext(), ContextDatabase::encodeTracked(), partmap< _linetype, _valuetype >::end(), Encoder::openElement(), and trackbase.
void ContextInternal::encodeContext (Encoder & encoder, const Address & addr, const uintm * vec) const private
Encode a single context block to a stream.
The blob is broken up into individual values and written out as a series of <set> elements within a parent <context_pointset> element.
Parameters
encoder is the stream encoder
addr is the address of the split point where the blob is valid
vec is the array of words holding the blob values
References Encoder::closeElement(), AddrSpace::encodeAttributes(), Address::getOffset(), Address::getSpace(), Encoder::openElement(), variables, Encoder::writeString(), and Encoder::writeUnsignedInteger().
Referenced by encode().
virtual const uintm* ContextInternal::getContext (const Address & addr) const inline virtual
Get the context blob of values associated with a given address.
Parameters
addr is the given address
Returns
the memory region holding the context values for the address
Implements ContextDatabase.
References database.
const uintm * ContextInternal::getContext (const Address & addr, uintb & first, uintb & last) const virtual
Get the context blob of values associated with a given address and its bounding offsets.
In addition to the memory region, the range of addresses for which the region is valid is passed back as offsets into the address space.
Parameters
addr is the given address
first will hold the starting offset of the valid range
last will hold the ending offset of the valid range
Returns
the memory region holding the context values for the address
Implements ContextDatabase.
References database, AddrSpace::getHighest(), Address::getOffset(), and Address::getSpace().
virtual int4 ContextInternal::getContextSize (void) const inline virtual
Retrieve the number of words (uintm) in a context blob.
Returns
the number of words
Implements ContextDatabase.
References size.
virtual uintm* ContextInternal::getDefaultValue (void) inline private virtual
Retrieve the memory region holding all default context values.
This fetches the active memory holding the default context values on top of which all other context values are overlaid.
Returns
the memory region holding all the default context values
Implements ContextDatabase.
References database.
Referenced by decodeContext().
virtual const uintm* ContextInternal::getDefaultValue (void) const inline private virtual
Retrieve the memory region holding all default context values.
This fetches the active memory holding the default context values on top of which all other context values are overlaid.
Returns
the memory region holding all the default context values
Implements ContextDatabase.
References database.
void ContextInternal::getRegionForSet (vector< uintm * > & res, const Address & addr1, const Address & addr2, int4 num, uintm mask) private virtual
Grab the context blob(s) for the given address range, marking bits that will be set.
This is an internal routine for obtaining the actual memory regions holding context values for the address range. This also informs the system which bits are getting set. A split is forced at the first address, and at least one memory region is passed back. The second address can be invalid in which case the memory region passed back is valid from the first address to whatever the next split point is.
Parameters
res will hold pointers to memory regions for the given range
addr1 is the starting address of the range
addr2 is (1 past) the last address of the range or is invalid
num is the word index for the context value that will be set
mask is a mask of the value being set (within its word)
Implements ContextDatabase.
References database, and Address::isInvalid().
Referenced by decodeContext().
void ContextInternal::getRegionToChangePoint (vector< uintm * > & res, const Address & addr, int4 num, uintm mask) private virtual
Grab the context blob(s) starting at the given address up to the first point of change.
This is an internal routine for obtaining the actual memory regions holding context values starting at the given address. A specific context value is specified, and all memory regions are returned up to the first address where that particular context value changes.
Parameters
res will hold pointers to memory regions being passed back
addr is the starting address of the regions to fetch
num is the word index for the specific context value being set
mask is a mask of the context value being set (within its word)
Implements ContextDatabase.
References database.
virtual TrackedSet& ContextInternal::getTrackedDefault (void) inline virtual
Get the set of default values for all tracked registers.
Returns
the list of TrackedContext objects
Implements ContextDatabase.
References partmap< _linetype, _valuetype >::defaultValue(), and trackbase.
virtual const TrackedSet& ContextInternal::getTrackedSet (const Address & addr) const inline virtual
Get the set of tracked register values associated with the given address.
Parameters
addr is the given address
Returns
the list of TrackedContext objects
Implements ContextDatabase.
References partmap< _linetype, _valuetype >::getValue(), and trackbase.
ContextBitRange & ContextInternal::getVariable (const string & nm) private virtual
Retrieve the context variable description object by name.
If the variable doesn't exist an exception is thrown.
Parameters
nm is the name of the context value
Returns
the ContextBitRange object matching the name
Implements ContextDatabase.
References variables.
Referenced by decodeContext().
const ContextBitRange & ContextInternal::getVariable (const string & nm) const private virtual
Retrieve the context variable description object by name.
If the variable doesn't exist an exception is thrown.
Parameters
nm is the name of the context value
Returns
the ContextBitRange object matching the name
Implements ContextDatabase.
References variables.
void ContextInternal::registerVariable (const string & nm, int4 sbit, int4 ebit) virtual
Register a new named context variable (as a bit range) with the database.
A new variable is registered by providing a name and the range of bits the value will occupy within the context blob. The full blob size is automatically increased if necessary. The variable must be contained within a single word, and all variables must be registered before any values can be set.
Parameters
nm is the name of the new variable
sbit is the position of the variable's most significant bit within the blob
ebit is the position of the variable's least significant bit within the blob
Implements ContextDatabase.
References database, size, and variables.
The documentation for this class was generated from the following files:
globalcontext.hh
globalcontext.cc