decompiler: PcodeOpRaw Class Reference
PcodeOpRaw Class Reference
A low-level representation of a single pcode operation.
#include <pcoderaw.hh>
Public Member Functions
void setBehavior (OpBehavior *be)
Set the opcode for this op.
OpBehavior * getBehavior (void) const
Retrieve the behavior for this op.
OpCode getOpcode (void) const
Get the opcode for this op.
void setSeqNum (const Address &a, uintm b)
Set the sequence number.
const SeqNum & getSeqNum (void) const
Retrieve the sequence number.
const Address & getAddr (void) const
Get address of this operation.
void setOutput (VarnodeData *o)
Set the output varnode for this op.
VarnodeData * getOutput (void) const
Retrieve the output varnode for this op.
void addInput (VarnodeData *i)
Add an additional input varnode to this op.
void clearInputs (void)
Remove all input varnodes to this op.
int4 numInput (void) const
Get the number of input varnodes to this op.
VarnodeData * getInput (int4 i) const
Get the i-th input varnode for this op.
Static Public Member Functions
static OpCode decode (Decoder &decoder, int4 isize, VarnodeData *invar, VarnodeData **outvar)
Decode the raw OpCode and input/output Varnode data for a PcodeOp.
Private Attributes
OpBehavior * behave
The opcode for this operation.
SeqNum seq
Identifying address and index of this operation.
VarnodeData * out
Output varnode triple.
vector< VarnodeData * > in
Raw varnode inputs to this op.
Detailed Description
A low-level representation of a single pcode operation.
This is just the minimum amount of data to represent a pcode operation An opcode, sequence number, optional output varnode and input varnodes
Member Function Documentation
void PcodeOpRaw::addInput (VarnodeData * i) inline
Add an additional input varnode to this op.
A PcodeOpRaw is initially created with no input varnodes. Inputs are added with this method. Varnodes are added in order, so the first addInput call creates input 0, for example.
Parameters
i is the varnode to be added as input
References in.
Referenced by PcodeEmitCache::dump().
void PcodeOpRaw::clearInputs (void) inline
Remove all input varnodes to this op.
If the inputs to a pcode operation need to be changed, this routine clears the existing inputs so new ones can be added.
References in.
OpCode PcodeOpRaw::decode (Decoder & decoder, int4 isize, VarnodeData * invar, VarnodeData ** outvar) static
Decode the raw OpCode and input/output Varnode data for a PcodeOp.
This assumes the <op> element is already open. Decode info suitable for call to PcodeEmit::dump. The output pointer is changed to null if there is no output for this op, otherwise the existing pointer is used to store the output.
Parameters
decoder is the stream decoder
isize is the (preparsed) number of input parameters for the p-code op
invar is an array of storage for the input Varnodes
outvar is a (handle) to the storage for the output Varnode
Returns
the p-code op OpCode
References ATTRIB_CODE, Decoder::closeElement(), VarnodeData::decode(), ELEM_SPACEID, Decoder::getAddrSpaceManager(), AddrSpaceManager::getConstantSpace(), VarnodeData::offset, Decoder::openElement(), Decoder::peekElement(), Decoder::readSignedInteger(), Decoder::readSpace(), VarnodeData::size, and VarnodeData::space.
Referenced by PcodeEmit::decodeOp().
const Address & PcodeOpRaw::getAddr (void) const inline
Get address of this operation.
This is a convenience function to get the address of the machine instruction (of which this pcode op is a translation)
Returns
the machine instruction address
References SeqNum::getAddr(), and seq.
Referenced by EmulateMemory::executeBranchind(), and EmulateMemory::executeCallind().
OpBehavior * PcodeOpRaw::getBehavior (void) const inline
Retrieve the behavior for this op.
Get the underlying behavior object for this pcode operation. From this object you can determine how the object evaluates inputs to get the output
Returns
the behavior object
References behave.
Referenced by EmulatePcodeCache::establishOp().
VarnodeData * PcodeOpRaw::getInput (int4 i) const inline
Get the i-th input varnode for this op.
Input varnodes are indexed starting at 0. This retrieves the input varnode by index. The index must be in range, or unpredicatable behavior will result. Use the numInput method to get the number of inputs.
Parameters
i is the index of the desired input
Returns
the desired input varnode
References in.
Referenced by BreakTableCallBack::doPcodeOpBreak(), EmulateMemory::executeBinary(), EmulateMemory::executeBranch(), EmulatePcodeCache::executeBranch(), EmulateMemory::executeBranchind(), EmulateMemory::executeCall(), EmulateMemory::executeCallind(), EmulateMemory::executeCbranch(), EmulateMemory::executeLoad(), EmulateMemory::executeStore(), and EmulateMemory::executeUnary().
OpCode PcodeOpRaw::getOpcode (void) const inline
Get the opcode for this op.
The possible types of pcode operations are enumerated by OpCode This routine retrieves the enumeration value for this particular op
Returns
the opcode value
References behave, and OpBehavior::getOpcode().
VarnodeData * PcodeOpRaw::getOutput (void) const inline
Retrieve the output varnode for this op.
Most pcode operations have an output varnode. This routine retrieves that varnode.
Returns
the output varnode or null if there is no output
References out.
Referenced by EmulateMemory::executeBinary(), EmulateMemory::executeLoad(), and EmulateMemory::executeUnary().
const SeqNum & PcodeOpRaw::getSeqNum (void) const inline
Retrieve the sequence number.
Every pcode operation has a sequence number which associates the operation with the address of the machine instruction being translated and an index number for this operation within the translation.
Returns
a reference to the sequence number
References seq.
int4 PcodeOpRaw::numInput (void) const inline
Get the number of input varnodes to this op.
Returns
the number of inputs
References in.
void PcodeOpRaw::setBehavior (OpBehavior * be) inline
Set the opcode for this op.
The core behavior for this operation is controlled by an OpBehavior object which knows how output is determined given inputs. This routine sets that object
Parameters
be is the behavior object
References behave.
Referenced by PcodeEmitCache::dump().
void PcodeOpRaw::setOutput (VarnodeData * o) inline
Set the output varnode for this op.
Most pcode operations output to a varnode. This routine sets what that varnode is.
Parameters
o is the varnode to set as output
References out.
Referenced by PcodeEmitCache::dump().
void PcodeOpRaw::setSeqNum (const Address & a, uintm b) inline
Set the sequence number.
Every pcode operation has a sequence number which associates the operation with the address of the machine instruction being translated and an order number which provides an index for this particular operation within the entire translation of the machine instruction
Parameters
a is the instruction address
b is the order number
References seq.
Referenced by PcodeEmitCache::dump().
The documentation for this class was generated from the following files:
pcoderaw.hh
pcoderaw.cc