decompiler: Sleigh Class Reference
Sleigh Class Reference
A full SLEIGH engine.
#include <sleigh.hh>
Public Member Functions
Sleigh (LoadImage *ld, ContextDatabase *c_db)
Constructor.
virtual ~Sleigh (void)
Destructor.
void reset (LoadImage *ld, ContextDatabase *c_db)
Reset the engine for a new program.
virtual void initialize (DocumentStorage &store)
virtual void registerContext (const string &name, int4 sbit, int4 ebit)
Add a new context variable to the model for this processor.
virtual void setContextDefault (const string &nm, uintm val)
Set the default value for a particular context variable.
virtual void allowContextSet (bool val) const
Toggle whether disassembly is allowed to affect context.
virtual int4 instructionLength (const Address &baseaddr) const
Get the length of a machine instruction.
virtual int4 oneInstruction (PcodeEmit &emit, const Address &baseaddr) const
Transform a single machine instruction into pcode.
virtual int4 printAssembly (AssemblyEmit &emit, const Address &baseaddr) const
Disassemble a single machine instruction.
Public Member Functions inherited from SleighBase
SleighBase (void)
Construct an uninitialized translator.
bool isInitialized (void) const
Return true if this is initialized.
virtual ~SleighBase (void)
Destructor.
virtual const VarnodeData & getRegister (const string &nm) const
Get a register as VarnodeData given its name.
virtual string getRegisterName (AddrSpace *base, uintb off, int4 size) const
Get the name of a register given its location.
virtual void getAllRegisters (map< VarnodeData, string > &reglist) const
Get a list of all register names and the corresponding location.
virtual void getUserOpNames (vector< string > &res) const
Get a list of all user-defined pcode ops.
SleighSymbol * findSymbol (const string &nm) const
Find a specific SLEIGH symbol by name in the current scope.
SleighSymbol * findSymbol (uintm id) const
Find a specific SLEIGH symbol by id.
SleighSymbol * findGlobalSymbol (const string &nm) const
Find a specific global SLEIGH symbol by name.
void saveXml (ostream &s) const
Write out the SLEIGH specification as an XML <sleigh> tag.
Public Member Functions inherited from Translate
Translate (void)
Constructor for the translator.
void setDefaultFloatFormats (void)
If no explicit float formats, set up default formats.
bool isBigEndian (void) const
Is the processor big endian?
const FloatFormat * getFloatFormat (int4 size) const
Get format for a particular floating point encoding.
int4 getAlignment (void) const
Get the instruction alignment for the processor.
uint4 getUniqueBase (void) const
Get the base offset for new temporary registers.
uint4 getUniqueStart (UniqueLayout layout) const
Get a tagged address within the unique space.
Public Member Functions inherited from AddrSpaceManager
AddrSpaceManager (void)
Construct an empty address space manager.
virtual ~AddrSpaceManager (void)
Destroy the manager.
int4 getDefaultSize (void) const
Get size of addresses for the default space.
AddrSpace * getSpaceByName (const string &nm) const
Get address space by name.
AddrSpace * getSpaceByShortcut (char sc) const
Get address space from its shortcut.
AddrSpace * getIopSpace (void) const
Get the internal pcode op space.
AddrSpace * getFspecSpace (void) const
Get the internal callspec space.
AddrSpace * getJoinSpace (void) const
Get the joining space.
AddrSpace * getStackSpace (void) const
Get the stack space for this processor.
AddrSpace * getUniqueSpace (void) const
Get the temporary register space for this processor.
AddrSpace * getDefaultCodeSpace (void) const
Get the default address space of this processor.
AddrSpace * getDefaultDataSpace (void) const
Get the default address space where data is stored.
AddrSpace * getConstantSpace (void) const
Get the constant space.
Address getConstant (uintb val) const
Get a constant encoded as an Address.
Address createConstFromSpace (AddrSpace *spc) const
Create a constant address encoding an address space.
Address resolveConstant (AddrSpace *spc, uintb val, int4 sz, const Address &point, uintb &fullEncoding) const
Resolve a native constant into an Address.
int4 numSpaces (void) const
Get the number of address spaces for this processor.
AddrSpace * getSpace (int4 i) const
Get an address space via its index.
AddrSpace * getNextSpaceInOrder (AddrSpace *spc) const
Get the next contiguous address space.
JoinRecord * findAddJoin (const vector< VarnodeData > &pieces, uint4 logicalsize)
Get (or create) JoinRecord for pieces.
JoinRecord * findJoin (uintb offset) const
Find JoinRecord for offset in the join space.
void setDeadcodeDelay (AddrSpace *spc, int4 delaydelta)
Set the deadcodedelay for a specific space.
void truncateSpace (const TruncationTag &tag)
Mark a space as truncated from its original size.
Address constructFloatExtensionAddress (const Address &realaddr, int4 realsize, int4 logicalsize)
Build a logically lower precision storage location for a bigger floating point register.
Address constructJoinAddress (const Translate *translate, const Address &hiaddr, int4 hisz, const Address &loaddr, int4 losz)
Build a logical whole from register pairs.
void renormalizeJoinAddress (Address &addr, int4 size)
Make sure a possibly offset join address has a proper JoinRecord.
Address parseAddressSimple (const string &val)
Parse a string with just an address space name and a hex offset.
Protected Member Functions
ParserContext * obtainContext (const Address &addr, int4 state) const
Obtain a parse tree for the instruction at the given address.
void resolve (ParserContext &pos) const
Generate a parse tree suitable for disassembly.
void resolveHandles (ParserContext &pos) const
Prepare the parse tree for p-code generation.
Protected Member Functions inherited from SleighBase
void buildXrefs (vector< string > &errorPairs)
Build register map. Collect user-ops and context-fields.
void reregisterContext (void)
Reregister context fields for a new executable.
void restoreXml (const Element *el)
Read a SLEIGH specification from XML.
Protected Member Functions inherited from Translate
void setBigEndian (bool val)
Set general endianness to big if val is true.
void setUniqueBase (uint4 val)
Set the base offset for new temporary registers.
Protected Member Functions inherited from AddrSpaceManager
AddrSpace * decodeSpace (Decoder &decoder, const Translate *trans)
Add a space to the model based an on XML tag.
void decodeSpaces (Decoder &decoder, const Translate *trans)
Restore address spaces in the model from an XML tag.
void setDefaultCodeSpace (int4 index)
Set the default address space (for code)
void setDefaultDataSpace (int4 index)
Set the default address space for data.
void setReverseJustified (AddrSpace *spc)
Set reverse justified property on this space.
void assignShortcut (AddrSpace *spc)
Select a shortcut character for a new space.
void markNearPointers (AddrSpace *spc, int4 size)
Mark that given space can be accessed with near pointers.
void insertSpace (AddrSpace *spc)
Add a new address space to the model.
void copySpaces (const AddrSpaceManager *op2)
Copy spaces from another manager.
void addSpacebasePointer (SpacebaseSpace *basespace, const VarnodeData &ptrdata, int4 truncSize, bool stackGrowth)
Set the base register of a spacebase space.
void insertResolver (AddrSpace *spc, AddressResolver *rsolv)
Override the base resolver for a space.
void setInferPtrBounds (const Range &range)
Set the range of addresses that can be inferred as pointers.
JoinRecord * findJoinInternal (uintb offset) const
Find JoinRecord for offset in the join space.
Private Member Functions
void clearForDelete (void)
Delete the context and disassembly caches.
Private Attributes
LoadImage * loader
The mapped bytes in the program.
ContextDatabase * context_db
Database of context values steering disassembly.
ContextCache * cache
Cache of recently used context values.
DisassemblyCache * discache
Cache of recently parsed instructions.
PcodeCacher pcode_cache
Cache of p-code data just prior to emitting.
Additional Inherited Members
Public Types inherited from Translate
enum UniqueLayout {
RUNTIME_BOOLEAN_INVERT =0, RUNTIME_RETURN_LOCATION =0x80, RUNTIME_BITRANGE_EA =0x100, INJECT =0x200,
ANALYSIS =0x10000000
}
Tagged addresses in the unique address space.
Static Public Attributes inherited from SleighBase
static const uint4 MAX_UNIQUE_SIZE = 128
Maximum size of a varnode in the unique space (should match value in SleighBase.java)
Protected Attributes inherited from SleighBase
SubtableSymbol * root
The root SLEIGH decoding symbol.
SymbolTable symtab
The SLEIGH symbol table.
uint4 maxdelayslotbytes
Maximum number of bytes in a delay-slot directive.
uint4 unique_allocatemask
Bits that are guaranteed to be zero in the unique allocation scheme.
uint4 numSections
Number of named sections.
SourceFileIndexer indexer
source file index used when generating SLEIGH constructor debug info
Protected Attributes inherited from Translate
int4 alignment
Byte modulo on which instructions are aligned.
vector< FloatFormat > floatformats
Floating point formats utilized by the processor.
Detailed Description
A full SLEIGH engine.
Its provided with a LoadImage of the bytes to be disassembled and a ContextDatabase.
Assembly is produced via the printAssembly() method, provided with an AssemblyEmit object and an Address.
P-code is produced via the oneInstruction() method, provided with a PcodeEmit object and an Address.
Constructor & Destructor Documentation
Sleigh::Sleigh (LoadImage * ld, ContextDatabase * c_db)
Constructor.
Parameters
ld is the LoadImage to draw program bytes from
c_db is the context database
References cache, context_db, discache, and loader.
Member Function Documentation
void Sleigh::allowContextSet (bool val) const virtual
Toggle whether disassembly is allowed to affect context.
By default the disassembly/pcode translation engine can change the global context, thereby affecting later disassembly. Context may be getting determined by something other than control flow in, the disassembly, in which case this function can turn off changes made by the disassembly
Parameters
val is true to allow context changes, false prevents changes
Reimplemented from Translate.
References ContextCache::allowSet(), and cache.
void Sleigh::initialize (DocumentStorage & store) virtual
The .sla file from the document store is loaded and cache objects are prepared
Parameters
store is the document store containing the main <sleigh> tag.
Implements Translate.
References cache, discache, AddrSpaceManager::getConstantSpace(), DocumentStorage::getTag(), SleighBase::isInitialized(), SleighBase::maxdelayslotbytes, SleighBase::reregisterContext(), SleighBase::restoreXml(), and SleighBase::unique_allocatemask.
int4 Sleigh::instructionLength (const Address & baseaddr) const virtual
Get the length of a machine instruction.
This method decodes an instruction at a specific address just enough to find the number of bytes it uses within the instruction stream.
Parameters
baseaddr is the Address of the instruction
Returns
the number of bytes in the instruction
Implements Translate.
References obtainContext().
ParserContext * Sleigh::obtainContext (const Address & addr, int4 state) const protected
Obtain a parse tree for the instruction at the given address.
The tree may be cached from a previous access. If the address has not been parsed, disassembly is performed, and a new parse tree is prepared. Depending on the desired state, the parse tree can be prepared either for disassembly or for p-code generation.
Parameters
addr is the given address of the instruction
state is the desired parse state.
Returns
the parse tree object (ParseContext)
References discache, DisassemblyCache::getParserContext(), resolve(), and resolveHandles().
Referenced by instructionLength(), oneInstruction(), and printAssembly().
int4 Sleigh::oneInstruction (PcodeEmit & emit, const Address & baseaddr) const virtual
Transform a single machine instruction into pcode.
This is the main interface to the pcode translation engine. The dump method in the emit object is invoked exactly once for each pcode operation in the translation for the machine instruction at the given address. This routine can throw either
UnimplError or
BadDataError
Parameters
emit is the tailored pcode emitting object
baseaddr is the Address of the machine instruction
Returns
the number of bytes in the machine instruction
Implements Translate.
References Translate::alignment, PcodeCacher::clear(), discache, PcodeCacher::emit(), LowlevelError::explain, AddrSpaceManager::getConstantSpace(), Address::getOffset(), AddrSpaceManager::getUniqueSpace(), UnimplError::instruction_length, obtainContext(), pcode_cache, PcodeCacher::resolveRelatives(), and SleighBase::unique_allocatemask.
int4 Sleigh::printAssembly (AssemblyEmit & emit, const Address & baseaddr) const virtual
Disassemble a single machine instruction.
This is the main interface to the disassembler for the processor. It disassembles a single instruction and returns the result to the application via the dump method in the emit object.
Parameters
emit is the disassembly emitting object
baseaddr is the address of the machine instruction to disassemble
Implements Translate.
References AssemblyEmit::dump(), and obtainContext().
void Sleigh::registerContext (const string & name, int4 sbit, int4 ebit) virtual
Add a new context variable to the model for this processor.
Add the name of a context register used by the processor and how that register is packed into the context state. This information is used by a ContextDatabase to associate names with context information and to pack context into a single state variable for the translation engine.
Parameters
name is the name of the new context variable
sbit is the first bit of the variable in the packed state
ebit is the last bit of the variable in the packed state
Reimplemented from Translate.
References context_db, and ContextDatabase::registerVariable().
void Sleigh::reset (LoadImage * ld, ContextDatabase * c_db)
Reset the engine for a new program.
Completely clear everything except the base and reconstruct with a new LoadImage and ContextDatabase
Parameters
ld is the new LoadImage
c_db is the new ContextDatabase
References cache, PcodeCacher::clear(), clearForDelete(), context_db, discache, loader, and pcode_cache.
void Sleigh::resolve (ParserContext & pos) const protected
Generate a parse tree suitable for disassembly.
Resolve all the constructors involved in the instruction at the indicated address
Parameters
pos is the parse object that will hold the resulting tree
References loader, LoadImage::loadFill(), and SleighBase::root.
Referenced by obtainContext().
void Sleigh::resolveHandles (ParserContext & pos) const protected
Prepare the parse tree for p-code generation.
Resolve handle templates for the given parse tree, assuming Constructors are already resolved.
Parameters
pos is the given parse tree
Referenced by obtainContext().
void Sleigh::setContextDefault (const string & name, uintm val) virtual
Set the default value for a particular context variable.
Set the value to be returned for a context variable when there are no explicit address ranges specifying a value for the variable.
Parameters
name is the name of the context variable
val is the value to be considered default
Reimplemented from Translate.
References context_db, and ContextDatabase::setVariableDefault().
The documentation for this class was generated from the following files:
sleigh.hh
sleigh.cc