decompiler: AddrSpaceManager Class Reference
AddrSpaceManager Class Reference
A manager for different address spaces.
#include <translate.hh>
Public Member Functions
AddrSpaceManager (void)
Construct an empty address space manager.
virtual ~AddrSpaceManager (void)
Destroy the manager.
int4 getDefaultSize (void) const
Get size of addresses for the default space.
AddrSpace * getSpaceByName (const string &nm) const
Get address space by name.
AddrSpace * getSpaceByShortcut (char sc) const
Get address space from its shortcut.
AddrSpace * getIopSpace (void) const
Get the internal pcode op space.
AddrSpace * getFspecSpace (void) const
Get the internal callspec space.
AddrSpace * getJoinSpace (void) const
Get the joining space.
AddrSpace * getStackSpace (void) const
Get the stack space for this processor.
AddrSpace * getUniqueSpace (void) const
Get the temporary register space for this processor.
AddrSpace * getDefaultCodeSpace (void) const
Get the default address space of this processor.
AddrSpace * getDefaultDataSpace (void) const
Get the default address space where data is stored.
AddrSpace * getConstantSpace (void) const
Get the constant space.
Address getConstant (uintb val) const
Get a constant encoded as an Address.
Address createConstFromSpace (AddrSpace *spc) const
Create a constant address encoding an address space.
Address resolveConstant (AddrSpace *spc, uintb val, int4 sz, const Address &point, uintb &fullEncoding) const
Resolve a native constant into an Address.
int4 numSpaces (void) const
Get the number of address spaces for this processor.
AddrSpace * getSpace (int4 i) const
Get an address space via its index.
AddrSpace * getNextSpaceInOrder (AddrSpace *spc) const
Get the next contiguous address space.
JoinRecord * findAddJoin (const vector< VarnodeData > &pieces, uint4 logicalsize)
Get (or create) JoinRecord for pieces.
JoinRecord * findJoin (uintb offset) const
Find JoinRecord for offset in the join space.
void setDeadcodeDelay (AddrSpace *spc, int4 delaydelta)
Set the deadcodedelay for a specific space.
void truncateSpace (const TruncationTag &tag)
Mark a space as truncated from its original size.
Address constructFloatExtensionAddress (const Address &realaddr, int4 realsize, int4 logicalsize)
Build a logically lower precision storage location for a bigger floating point register.
Address constructJoinAddress (const Translate *translate, const Address &hiaddr, int4 hisz, const Address &loaddr, int4 losz)
Build a logical whole from register pairs.
void renormalizeJoinAddress (Address &addr, int4 size)
Make sure a possibly offset join address has a proper JoinRecord.
Address parseAddressSimple (const string &val)
Parse a string with just an address space name and a hex offset.
Protected Member Functions
AddrSpace * decodeSpace (Decoder &decoder, const Translate *trans)
Add a space to the model based an on XML tag.
void decodeSpaces (Decoder &decoder, const Translate *trans)
Restore address spaces in the model from an XML tag.
void setDefaultCodeSpace (int4 index)
Set the default address space (for code)
void setDefaultDataSpace (int4 index)
Set the default address space for data.
void setReverseJustified (AddrSpace *spc)
Set reverse justified property on this space.
void assignShortcut (AddrSpace *spc)
Select a shortcut character for a new space.
void markNearPointers (AddrSpace *spc, int4 size)
Mark that given space can be accessed with near pointers.
void insertSpace (AddrSpace *spc)
Add a new address space to the model.
void copySpaces (const AddrSpaceManager *op2)
Copy spaces from another manager.
void addSpacebasePointer (SpacebaseSpace *basespace, const VarnodeData &ptrdata, int4 truncSize, bool stackGrowth)
Set the base register of a spacebase space.
void insertResolver (AddrSpace *spc, AddressResolver *rsolv)
Override the base resolver for a space.
void setInferPtrBounds (const Range &range)
Set the range of addresses that can be inferred as pointers.
JoinRecord * findJoinInternal (uintb offset) const
Find JoinRecord for offset in the join space.
Private Attributes
vector< AddrSpace * > baselist
Every space we know about for this architecture.
vector< AddressResolver * > resolvelist
Special constant resolvers.
map< string, AddrSpace * > name2Space
Map from name -> space.
map< int4, AddrSpace * > shortcut2Space
Map from shortcut -> space.
AddrSpace * constantspace
Quick reference to constant space.
AddrSpace * defaultcodespace
Default space where code lives, generally main RAM.
AddrSpace * defaultdataspace
Default space where data lives.
AddrSpace * iopspace
Space for internal pcode op pointers.
AddrSpace * fspecspace
Space for internal callspec pointers.
AddrSpace * joinspace
Space for unifying split variables.
AddrSpace * stackspace
Stack space associated with processor.
AddrSpace * uniqspace
Temporary space associated with processor.
uintb joinallocate
Next offset to be allocated in join space.
set< JoinRecord
*, JoinRecordCompare > splitset
Different splits that have been defined in join space.
vector< JoinRecord * > splitlist
JoinRecords indexed by join address.
Detailed Description
A manager for different address spaces.
Allow creation, lookup by name, lookup by shortcut, lookup by name, and iteration over address spaces
Constructor & Destructor Documentation
AddrSpaceManager::AddrSpaceManager (void)
Construct an empty address space manager.
Initialize manager containing no address spaces. All the cached space slots are set to null.
References constantspace, defaultcodespace, defaultdataspace, fspecspace, iopspace, joinallocate, joinspace, stackspace, and uniqspace.
AddrSpaceManager::~AddrSpaceManager (void) virtual
Destroy the manager.
Base destructor class, cleans up AddrSpace pointers which must be explicited created via new
References baselist, AddrSpace::refcount, resolvelist, and splitlist.
Member Function Documentation
void AddrSpaceManager::addSpacebasePointer (SpacebaseSpace * basespace, const VarnodeData & ptrdata, int4 truncSize, bool stackGrowth) protected
Set the base register of a spacebase space.
Perform the privileged act of associating a base register with an existing virtual space
Parameters
basespace is the virtual space
ptrdata is the location data for the base register
truncSize is the size of the space covered by the base register
stackGrowth is true if the stack grows "normally" towards address 0
References SpacebaseSpace::setBaseRegister().
void AddrSpaceManager::assignShortcut (AddrSpace * spc) protected
Select a shortcut character for a new space.
Assign a shortcut character to the given address space. This routine makes use of the desired type of the new space and info about shortcuts for spaces that already exist to pick a unique and consistent character. This method also builds up a map from short to AddrSpace object.
Parameters
spc is the given AddrSpace
References AddrSpace::getName(), AddrSpace::getType(), IPTR_CONSTANT, IPTR_FSPEC, IPTR_INTERNAL, IPTR_IOP, IPTR_JOIN, IPTR_PROCESSOR, IPTR_SPACEBASE, AddrSpace::shortcut, and shortcut2Space.
Referenced by insertSpace().
Address AddrSpaceManager::constructFloatExtensionAddress (const Address & realaddr, int4 realsize, int4 logicalsize)
Build a logically lower precision storage location for a bigger floating point register.
This handles the situation where we need to find a logical address to hold the lower precision floating-point value that is stored in a bigger register If the logicalsize (precision) requested matches the -realsize- of the register just return the real address. Otherwise construct a join address to hold the logical value
Parameters
realaddr is the address of the real floating-point register
realsize is the size of the real floating-point register
logicalsize is the size (lower precision) size of the logical value
References findAddJoin(), VarnodeData::getAddr(), Address::getOffset(), Address::getSpace(), and JoinRecord::getUnified().
Address AddrSpaceManager::constructJoinAddress (const Translate * translate, const Address & hiaddr, int4 hisz, const Address & loaddr, int4 losz)
Build a logical whole from register pairs.
This handles the common case, of trying to find a join address given a high location and a low location. This may not return an address in the join address space. It checks for the case where the two pieces are contiguous locations in a mappable space, in which case it just returns the containing address
Parameters
translate is the Translate object used to find registers
hiaddr is the address of the most significant piece to be joined
hisz is the size of the most significant piece
loaddr is the address of the least significant piece
losz is the size of the least significant piece
Returns
an address representing the start of the joined range
References findAddJoin(), VarnodeData::getAddr(), getDefaultCodeSpace(), Address::getOffset(), Translate::getRegisterName(), Address::getSpace(), AddrSpace::getType(), JoinRecord::getUnified(), IPTR_PROCESSOR, IPTR_SPACEBASE, Address::isBigEndian(), and Address::isContiguous().
void AddrSpaceManager::copySpaces (const AddrSpaceManager * op2) protected
Copy spaces from another manager.
Different managers may need to share the same spaces. I.e. if different programs being analyzed share the same processor. This routine pulls in a reference of every space in -op2- in order to manage it from within -this-
Parameters
op2 is a pointer to space manager being copied
References baselist, getDefaultCodeSpace(), getDefaultDataSpace(), AddrSpace::getIndex(), insertSpace(), setDefaultCodeSpace(), and setDefaultDataSpace().
Address AddrSpaceManager::createConstFromSpace (AddrSpace * spc) const inline
Create a constant address encoding an address space.
This routine is used to encode a pointer to an address space as a constant Address, for use in LOAD and STORE operations. This is used internally and is slightly more efficient than storing the formal index of the space param spc is the space pointer to be encoded
Returns
the encoded Address
References constantspace.
AddrSpace * AddrSpaceManager::decodeSpace (Decoder & decoder, const Translate * trans) protected
Add a space to the model based an on XML tag.
The initialization of address spaces is the same across all variants of the Translate object. This routine initializes a single address space from a decoder element. It knows which class derived from AddrSpace to instantiate based on the ElementId.
Parameters
decoder is the stream decoder
trans is the translator object to be associated with the new space
Returns
a pointer to the initialized AddrSpace
References AddrSpace::decode(), IPTR_PROCESSOR, and Decoder::peekElement().
Referenced by decodeSpaces().
void AddrSpaceManager::decodeSpaces (Decoder & decoder, const Translate * trans) protected
Restore address spaces in the model from an XML tag.
This routine initializes (almost) all the address spaces used for a particular processor by using a <spaces> element, which contains child elements for the specific address spaces. This also instantiates the builtin constant space. It should probably also instantiate the iop, fspec, and join spaces, but this is currently done by the Architecture class.
Parameters
decoder is the stream decoder
trans is the processor translator to be associated with the spaces
References Decoder::closeElement(), decodeSpace(), AddrSpace::getIndex(), getSpaceByName(), insertSpace(), Decoder::openElement(), Decoder::peekElement(), Decoder::readString(), and setDefaultCodeSpace().
Referenced by SleighBase::restoreXml().
JoinRecord * AddrSpaceManager::findAddJoin (const vector< VarnodeData > & pieces, uint4 logicalsize)
Get (or create) JoinRecord for pieces.
Given a list of memory locations, the pieces, either find a pre-existing JoinRecord or create a JoinRecord that represents the logical joining of the pieces.
Parameters
pieces if the list memory locations to be joined
logicalsize of a single piece join, or zero
Returns
a pointer to the JoinRecord
References joinallocate, joinspace, VarnodeData::offset, JoinRecord::pieces, VarnodeData::size, VarnodeData::space, splitlist, splitset, and JoinRecord::unified.
Referenced by constructFloatExtensionAddress(), constructJoinAddress(), JoinSpace::decodeAttributes(), JoinSpace::read(), and renormalizeJoinAddress().
JoinRecord * AddrSpaceManager::findJoin (uintb offset) const
Find JoinRecord for offset in the join space.
Given a specific offset into the join address space, recover the JoinRecord that lists the pieces corresponding to that offset. The offset must originally have come from a JoinRecord returned by findAddJoin, otherwise this method throws an exception.
Parameters
offset is an offset into the join space
Returns
the JoinRecord for that offset
References VarnodeData::offset, splitlist, and JoinRecord::unified.
Referenced by JoinSpace::encodeAttributes(), and JoinSpace::printRaw().
JoinRecord * AddrSpaceManager::findJoinInternal (uintb offset) const protected
Find JoinRecord for offset in the join space.
Given a specific offset into the join address space, recover the JoinRecord that contains the offset, as a range in the join address space. If there is no existing record, null is returned.
Parameters
offset is an offset into the join space
Returns
the JoinRecord containing that offset or null
References VarnodeData::offset, VarnodeData::size, splitlist, and JoinRecord::unified.
Referenced by renormalizeJoinAddress().
Address AddrSpaceManager::getConstant (uintb val) const inline
Get a constant encoded as an Address.
This routine encodes a specific value as a constant address. I.e. the address space of the resulting Address will be the constant space, and the offset will be the value.
Parameters
val is the constant value to encode
Returns
the constant address
References constantspace.
AddrSpace * AddrSpaceManager::getConstantSpace (void) const inline
Get the constant space.
Pcode represents constant values within an operation as offsets within a special constant address space. (See ConstantSpace)
Returns
a pointer to the constant space
References constantspace.
Referenced by SleighCompile::createCrossBuild(), SleighCompile::createMacroUse(), PcodeOpRaw::decode(), SleighCompile::finalizeSections(), Sleigh::initialize(), Sleigh::oneInstruction(), SleighCompile::predefinedSymbols(), and MacroBuilder::transferOp().
AddrSpace * AddrSpaceManager::getDefaultCodeSpace (void) const inline
Get the default address space of this processor.
Most processors have a main address bus, on which the bulk of the processor's RAM is mapped. This matches SLEIGH's notion of the default space. For Harvard architectures, this is the space where code exists (as opposed to data).
Returns
a pointer to the default code space
References defaultcodespace.
Referenced by constructJoinAddress(), copySpaces(), VarnodeData::decodeFromAttributes(), Range::decodeFromAttributes(), SleighCompile::newSpace(), SleighCompile::process(), Range::Range(), and SleighBase::saveXml().
AddrSpace * AddrSpaceManager::getDefaultDataSpace (void) const inline
Get the default address space where data is stored.
Return the default address space for holding data. For most processors, this is just the main RAM space and is the same as the default code space. For Harvard architectures, this is the space where data is stored (as opposed to code).
Returns
a pointer to the default data space
References defaultdataspace.
Referenced by copySpaces(), and parseAddressSimple().
int4 AddrSpaceManager::getDefaultSize (void) const inline
Get size of addresses for the default space.
Return the size of addresses for the processor's official default space. This space is usually the main RAM databus.
Returns
the size of an address in bytes
References defaultcodespace, and AddrSpace::getAddrSize().
Referenced by AddrSpace::read().
AddrSpace * AddrSpaceManager::getFspecSpace (void) const inline
Get the internal callspec space.
There is a special address space reserved for encoding pointers to the FuncCallSpecs object as addresses. This allows direct pointers to be hidden within an operation, when manipulating pcode internally. (See FspecSpace)
Returns
a pointer to the address space
References fspecspace.
AddrSpace * AddrSpaceManager::getIopSpace (void) const inline
Get the internal pcode op space.
There is a special address space reserved for encoding pointers to pcode operations as addresses. This allows a direct pointer to be hidden within an operation, when manipulating pcode internally. (See IopSpace)
Returns
a pointer to the address space
References iopspace.
AddrSpace * AddrSpaceManager::getJoinSpace (void) const inline
Get the joining space.
There is a special address space reserved for providing a logical contiguous memory location for variables that are really split between two physical locations. This allows the the decompiler to work with the logical value. (See JoinSpace)
Returns
a pointer to the address space
References joinspace.
AddrSpace * AddrSpaceManager::getNextSpaceInOrder (AddrSpace * spc) const
Get the next contiguous address space.
Get the next space in the absolute order of addresses. This ordering is determined by the AddrSpace index.
Parameters
spc is the pointer to the space being queried
Returns
the pointer to the next space in absolute order
References baselist, and AddrSpace::getIndex().
Referenced by Range::getLastAddrOpen().
AddrSpace * AddrSpaceManager::getSpace (int4 i) const inline
Get an address space via its index.
This retrieves a specific address space via its formal index. All spaces have an index, and in conjunction with the numSpaces method, this method can be used to iterate over all spaces.
Parameters
i is the index of the address space
Returns
a pointer to the desired space
References baselist.
Referenced by SleighBase::saveXml().
AddrSpace * AddrSpaceManager::getSpaceByName (const string & nm) const
Get address space by name.
All address spaces have a unique name associated with them. This routine retrieves the AddrSpace object based on the desired name.
Parameters
nm is the name of the address space
Returns
a pointer to the AddrSpace object
References name2Space.
Referenced by JoinSpace::decodeAttributes(), decodeSpaces(), parseAddressSimple(), Range::Range(), XmlDecode::readSpace(), and truncateSpace().
AddrSpace * AddrSpaceManager::getSpaceByShortcut (char sc) const
Get address space from its shortcut.
All address spaces have a unique shortcut (ASCII) character assigned to them. This routine retrieves an AddrSpace object given a specific shortcut.
Parameters
sc is the shortcut character
Returns
a pointer to an AddrSpace
References shortcut2Space.
Referenced by JoinSpace::read().
AddrSpace * AddrSpaceManager::getStackSpace (void) const inline
Get the stack space for this processor.
Most processors have registers and instructions that are reserved for implementing a stack. In the pcode translation, these are translated into locations and operations on a dedicated stack address space. (See SpacebaseSpace)
Returns
a pointer to the stack space
References stackspace.
AddrSpace * AddrSpaceManager::getUniqueSpace (void) const inline
Get the temporary register space for this processor.
Both the pcode translation process and the simplification process need access to a pool of temporary registers that can be used for moving data around without affecting the address spaces used to formally model the processor's RAM and registers. These temporary locations are all allocated from a dedicated address space, referred to as the unique space. (See UniqueSpace)
Returns
a pointer to the unique space
References uniqspace.
Referenced by Sleigh::oneInstruction(), SleighCompile::predefinedSymbols(), SleighCompile::setResultStarVarnode(), and MacroBuilder::transferOp().
void AddrSpaceManager::insertResolver (AddrSpace * spc, AddressResolver * rsolv) protected
Override the base resolver for a space.
Provide a new specialized resolver for a specific AddrSpace. The manager takes ownership of resolver.
Parameters
spc is the space to which the resolver is associated
rsolv is the new resolver object
References AddrSpace::getIndex(), and resolvelist.
void AddrSpaceManager::insertSpace (AddrSpace * spc) protected
Add a new address space to the model.
This adds a previously instantiated address space (AddrSpace) to the model for this processor. It checks a set of indexing and naming conventions for the space and throws an exception if the conventions are violated. Should only be called during initialization.
Todo:
This really shouldn't be public. Need to move the allocation of iop, fspec, and join out of Architecture
Parameters
spc the address space to insert
References assignShortcut(), baselist, constantspace, fspecspace, AddrSpace::getContain(), AddrSpace::getName(), AddrSpace::getType(), AddrSpace::index, ConstantSpace::INDEX, OtherSpace::INDEX, iopspace, IPTR_CONSTANT, IPTR_FSPEC, IPTR_INTERNAL, IPTR_IOP, IPTR_JOIN, IPTR_PROCESSOR, IPTR_SPACEBASE, AddrSpace::isOtherSpace(), AddrSpace::isOverlay(), joinspace, ConstantSpace::NAME, UniqueSpace::NAME, JoinSpace::NAME, name2Space, AddrSpace::overlaybase, AddrSpace::refcount, AddrSpace::setFlags(), stackspace, and uniqspace.
Referenced by copySpaces(), decodeSpaces(), SleighCompile::newSpace(), and SleighCompile::predefinedSymbols().
void AddrSpaceManager::markNearPointers (AddrSpace * spc, int4 size) protected
Mark that given space can be accessed with near pointers.
Parameters
spc is the AddrSpace to mark
size is the (minimum) size of a near pointer in bytes
References AddrSpace::addressSize, AddrSpace::has_nearpointers, AddrSpace::minimumPointerSize, and AddrSpace::setFlags().
int4 AddrSpaceManager::numSpaces (void) const inline
Get the number of address spaces for this processor.
This returns the total number of address spaces used by the processor, including all special spaces, like the constant space and the iop space.
Returns
the number of spaces
References baselist.
Referenced by SleighCompile::newSpace(), SleighCompile::predefinedSymbols(), and SleighBase::saveXml().
Address AddrSpaceManager::parseAddressSimple (const string & val)
Parse a string with just an address space name and a hex offset.
The string must contain a hexadecimal offset. The offset may be optionally prepended with "0x". The string may optionally start with the name of the address space to associate with the offset, followed by ':' to separate it from the offset. If the name is not present, the default data space is assumed.
Parameters
val is the string to parse
Returns
the parsed address
References AddrSpace::addressToByte(), getDefaultDataSpace(), getSpaceByName(), and AddrSpace::getWordSize().
void AddrSpaceManager::renormalizeJoinAddress (Address & addr, int4 size)
Make sure a possibly offset join address has a proper JoinRecord.
If an Address in the join AddressSpace is shifted from its original offset, it may no longer have a valid JoinRecord. The shift or size change may even make the address of one of the pieces a more natural representation. Given a new Address and size, this method decides if there is a matching JoinRecord. If not it either constructs a new JoinRecord or computes the address within the containing piece. The given Address is changed if necessary either to the offset corresponding to the new JoinRecord or to a normal non-join Address.
Parameters
addr is the given Address
size is the size of the range in bytes
References findAddJoin(), findJoinInternal(), JoinRecord::getEquivalentAddress(), Address::getOffset(), Address::isInvalid(), VarnodeData::offset, JoinRecord::pieces, VarnodeData::size, VarnodeData::space, and JoinRecord::unified.
Referenced by Address::renormalize().
Address AddrSpaceManager::resolveConstant (AddrSpace * spc, uintb val, int4 sz, const Address & point, uintb & fullEncoding) const
Resolve a native constant into an Address.
If there is a special resolver for the AddrSpace, this is invoked, otherwise basic wordsize conversion and wrapping is performed. If the address encoding is partial (as in a near pointer) and the full encoding can be recovered, it is passed back. The sz parameter indicates the number of bytes in constant and is used to determine if the constant is a partial or full pointer encoding. A value of -1 indicates the value is known to be a full encoding.
Parameters
spc is the space to generate the address from
val is the constant encoding of the address
sz is the size of the constant encoding (or -1)
point is the context address (for recovering full encoding info if necessary)
fullEncoding is used to pass back the recovered full encoding of the pointer
Returns
the formal Address associated with the encoding
References AddrSpace::addressToByte(), AddrSpace::getIndex(), AddrSpace::getWordSize(), AddressResolver::resolve(), resolvelist, and AddrSpace::wrapOffset().
void AddrSpaceManager::setDeadcodeDelay (AddrSpace * spc, int4 delaydelta)
Set the deadcodedelay for a specific space.
Set the number of passes for a specific AddrSpace before deadcode removal is allowed for that space.
Parameters
spc is the AddrSpace to change
delaydelta is the number of rounds to the delay should be set to
References AddrSpace::deadcodedelay.
void AddrSpaceManager::setDefaultCodeSpace (int4 index) protected
Set the default address space (for code)
Once all the address spaces have been initialized, this routine should be called once to establish the official default space for the processor, via its index. Should only be called during initialization.
Parameters
index is the index of the desired default space
References baselist, defaultcodespace, and defaultdataspace.
Referenced by copySpaces(), decodeSpaces(), and SleighCompile::newSpace().
void AddrSpaceManager::setDefaultDataSpace (int4 index) protected
Set the default address space for data.
If the architecture has different code and data spaces, this routine can be called to set the data space after the code space has been set.
Parameters
index is the index of the desired default space
References baselist, defaultcodespace, and defaultdataspace.
Referenced by copySpaces().
void AddrSpaceManager::setInferPtrBounds (const Range & range) protected
Set the range of addresses that can be inferred as pointers.
This method establishes for a single address space, what range of constants are checked as possible symbol starts, when it is not known apriori that a constant is a pointer.
Parameters
range is the range of values for a single address space
References Range::getFirst(), Range::getLast(), Range::getSpace(), AddrSpace::pointerLowerBound, and AddrSpace::pointerUpperBound.
void AddrSpaceManager::setReverseJustified (AddrSpace * spc) protected
Set reverse justified property on this space.
For spaces with alignment restrictions, the address of a small variable must be justified within a larger aligned memory word, usually either to the left boundary for little endian encoding or to the right boundary for big endian encoding. Some compilers justify small variables to the opposite side of the one indicated by the endianness. Setting this property on a space causes the decompiler to use this justification
References AddrSpace::reverse_justification, and AddrSpace::setFlags().
void AddrSpaceManager::truncateSpace (const TruncationTag & tag)
Mark a space as truncated from its original size.
Mark the named space as truncated from its original size
Parameters
tag is a description of the space and how it should be truncated
References TruncationTag::getName(), TruncationTag::getSize(), getSpaceByName(), and AddrSpace::truncateSpace().
The documentation for this class was generated from the following files:
translate.hh
translate.cc