decompiler: TruncationTag Class Reference
TruncationTag Class Reference
Object for describing how a space should be truncated.
#include <translate.hh>
Public Member Functions
void decode (Decoder &decoder)
Restore this from a stream.
const string & getName (void) const
Get name of address space being truncated.
uint4 getSize (void) const
Size (of pointers) for new truncated space.
Private Attributes
string spaceName
Name of space to be truncated.
uint4 size
Size truncated addresses into the space.
Detailed Description
Object for describing how a space should be truncated.
This can turn up in various XML configuration files and essentially acts as a command to override the size of an address space as defined by the architecture
Member Function Documentation
void TruncationTag::decode (Decoder & decoder)
Restore this from a stream.
Parse a <truncate_space> element to configure this object
Parameters
decoder is the stream decoder
References Decoder::closeElement(), Decoder::openElement(), Decoder::readString(), Decoder::readUnsignedInteger(), size, and spaceName.
The documentation for this class was generated from the following files:
translate.hh
translate.cc