decompiler: Element Class Reference
Element Class Reference
An XML element. A node in the DOM tree.
#include <xml.hh>
Public Member Functions
Element (Element *par)
Constructor given a parent Element.
~Element (void)
Destructor.
void setName (const string &nm)
Set the local name of the element.
void addContent (const char *str, int4 start, int4 length)
Append new character content to this element.
void addChild (Element *child)
Add a new child Element to the model, with this as the parent.
void addAttribute (const string &nm, const string &vl)
Add a new name/value attribute pair to this element.
Element * getParent (void) const
Get the parent Element.
const string & getName (void) const
Get the local name of this element.
const List & getChildren (void) const
Get the list of child elements.
const string & getContent (void) const
Get the character content of this element.
const string & getAttributeValue (const string &nm) const
Get an attribute value by name.
int4 getNumAttributes (void) const
Get the number of attributes for this element.
const string & getAttributeName (int4 i) const
Get the name of the i-th attribute.
const string & getAttributeValue (int4 i) const
Get the value of the i-th attribute.
Protected Attributes
Element * parent
The parent Element (or null)
List children
A list of child Element objects.
Private Attributes
string name
The (local) name of the element.
string content
Character content of the element.
vector< string > attr
A list of attribute names for this element.
vector< string > value
a (corresponding) list of attribute values for this element
Detailed Description
An XML element. A node in the DOM tree.
This is the main node for the in-memory representation of the XML (DOM) tree.
Member Function Documentation
void Element::addAttribute (const string & nm, const string & vl) inline
Add a new name/value attribute pair to this element.
Parameters
nm is the name of the attribute
vl is the value of the attribute
References attr, and value.
void Element::addChild (Element * child) inline
Add a new child Element to the model, with this as the parent.
Parameters
child is the new child Element
References children.
void Element::addContent (const char * str, int4 start, int4 length) inline
Append new character content to this element.
Parameters
str is an array of character data
start is the index of the first character to append
length is the number of characters to append
References content.
const string& Element::getAttributeValue (const string & nm) const
Get an attribute value by name.
Look up the value for the given attribute name and return it. An exception is thrown if the attribute does not exist.
Parameters
nm is the name of the attribute
Returns
the corresponding attribute value
Referenced by XmlDecode::readBool(), XmlDecode::readSignedInteger(), XmlDecode::readSignedIntegerExpectString(), XmlDecode::readSpace(), XmlDecode::readString(), XmlDecode::readUnsignedInteger(), SleighBase::restoreXml(), and FloatFormat::restoreXml().
The documentation for this class was generated from the following file:
xml.hh