decompiler: Decoder Class Reference
Decoder Class Reference abstract
A class for reading structured data from a stream.
#include <marshal.hh>
Public Member Functions
Decoder (const AddrSpaceManager *spc)
Base constructor.
const AddrSpaceManager * getAddrSpaceManager (void) const
Get the manager used for address space decoding.
virtual ~Decoder (void)
Destructor.
virtual void ingestStream (istream &s)=0
Prepare to decode a given stream.
virtual uint4 peekElement (void)=0
Peek at the next child element of the current parent, without traversing in (opening) it.
virtual uint4 openElement (void)=0
Open (traverse into) the next child element of the current parent.
virtual uint4 openElement (const ElementId &elemId)=0
Open (traverse into) the next child element, which must be of a specific type.
virtual void closeElement (uint4 id)=0
Close the current element.
virtual void closeElementSkipping (uint4 id)=0
Close the current element, skipping any child elements that have not yet been parsed.
virtual uint4 getNextAttributeId (void)=0
Get the next attribute id for the current element.
virtual void rewindAttributes (void)=0
Reset attribute traversal for the current element.
virtual bool readBool (void)=0
Parse the current attribute as a boolean value.
virtual bool readBool (const AttributeId &attribId)=0
Find and parse a specific attribute in the current element as a boolean value.
virtual intb readSignedInteger (void)=0
Parse the current attribute as a signed integer value.
virtual intb readSignedInteger (const AttributeId &attribId)=0
Find and parse a specific attribute in the current element as a signed integer.
virtual intb readSignedIntegerExpectString (const string &expect, intb expectval)=0
Parse the current attribute as either a signed integer value or a string.
virtual intb readSignedIntegerExpectString (const AttributeId &attribId, const string &expect, intb expectval)=0
Find and parse a specific attribute in the current element as either a signed integer or a string.
virtual uintb readUnsignedInteger (void)=0
Parse the current attribute as an unsigned integer value.
virtual uintb readUnsignedInteger (const AttributeId &attribId)=0
Find and parse a specific attribute in the current element as an unsigned integer.
virtual string readString (void)=0
Parse the current attribute as a string.
virtual string readString (const AttributeId &attribId)=0
Find the specific attribute in the current element and return it as a string.
virtual AddrSpace * readSpace (void)=0
Parse the current attribute as an address space.
virtual AddrSpace * readSpace (const AttributeId &attribId)=0
Find the specific attribute in the current element and return it as an address space.
void skipElement (void)
Skip parsing of the next element.
Protected Attributes
const AddrSpaceManager * spcManager
Manager for decoding address space attributes.
Detailed Description
A class for reading structured data from a stream.
All data is loosely structured as with an XML document. A document contains a nested set of elements, with labels corresponding to the ElementId class. A single element can hold zero or more attributes and zero or more child elements. An attribute holds a primitive data element (bool, integer, string) and is labeled by an AttributeId. The document is traversed using a sequence of openElement() and closeElement() calls, intermixed with read*() calls to extract the data. The elements are traversed in a depth first order. Attributes within an element can be traversed in order using repeated calls to the getNextAttributeId() method, followed by a calls to one of the read*(void) methods to extract the data. Alternately a read*(AttributeId) call can be used to extract data for an attribute known to be in the element. There is a special content attribute whose data can be extracted using a read*(AttributeId) call that is passed the special ATTRIB_CONTENT id. This attribute will not be traversed by getNextAttribute().
Member Function Documentation
virtual void Decoder::closeElement (uint4 id) pure virtual
Close the current element.
The data for the current element is considered fully processed. If the element has additional children, an exception is thrown. The stream must indicate the end of the element in some way.
Parameters
id is the id of the element to close (which must be the current element)
Implemented in PackedDecode, and XmlDecode.
Referenced by VarnodeData::decode(), TrackedContext::decode(), TruncationTag::decode(), PcodeOpRaw::decode(), SeqNum::decode(), AddrSpace::decode(), SpacebaseSpace::decode(), Range::decode(), RangeProperties::decode(), RangeList::decode(), OverlaySpace::decode(), ContextInternal::decode(), ContextInternal::decodeContext(), ContextInternal::decodeFromSpec(), PcodeEmit::decodeOp(), and AddrSpaceManager::decodeSpaces().
virtual void Decoder::closeElementSkipping (uint4 id) pure virtual
Close the current element, skipping any child elements that have not yet been parsed.
This closes the given element, which must be current. If there are child elements that have not been parsed, this is not considered an error, and they are skipped over in the parse.
Parameters
id is the id of the element to close (which must be the current element)
Implemented in PackedDecode, and XmlDecode.
Referenced by skipElement().
virtual uint4 Decoder::getNextAttributeId (void) pure virtual
Get the next attribute id for the current element.
Attributes are automatically set up for traversal using this method, when the element is opened. If all attributes have been traversed (or there are no attributes), 0 is returned.
Returns
the id of the next attribute or 0
Implemented in PackedDecode, and XmlDecode.
Referenced by SeqNum::decode(), RangeProperties::decode(), ContextInternal::decode(), AddrSpace::decodeAttributes(), JoinSpace::decodeAttributes(), AddrSpace::decodeBasicAttributes(), VarnodeData::decodeFromAttributes(), and Range::decodeFromAttributes().
virtual void Decoder::ingestStream (istream & s) pure virtual
Prepare to decode a given stream.
Called once before any decoding. Currently this is assumed to make an internal copy of the stream data, i.e. the input stream is cleared before any decoding takes place.
Parameters
s is the given input stream to be decode
Returns
true if the stream was fully ingested
Implemented in PackedDecode, and XmlDecode.
virtual uint4 Decoder::openElement (void) pure virtual
Open (traverse into) the next child element of the current parent.
The child becomes the current parent. The list of attributes is initialized for use with getNextAttributeId.
Returns
the id of the child element
Implemented in PackedDecode, and XmlDecode.
Referenced by VarnodeData::decode(), TrackedContext::decode(), TruncationTag::decode(), PcodeOpRaw::decode(), SeqNum::decode(), AddrSpace::decode(), SpacebaseSpace::decode(), Range::decode(), RangeProperties::decode(), RangeList::decode(), OverlaySpace::decode(), ContextInternal::decode(), ContextInternal::decodeContext(), ContextInternal::decodeFromSpec(), PcodeEmit::decodeOp(), AddrSpaceManager::decodeSpaces(), and skipElement().
virtual uint4 Decoder::openElement (const ElementId & elemId) pure virtual
Open (traverse into) the next child element, which must be of a specific type.
The child becomes the current parent, and its attributes are initialized for use with getNextAttributeId. The child must match the given element id or an exception is thrown.
Parameters
elemId is the given element id to match
Returns
the id of the child element
Implemented in PackedDecode, and XmlDecode.
virtual uint4 Decoder::peekElement (void) pure virtual
Peek at the next child element of the current parent, without traversing in (opening) it.
The element id is returned, which can be compared to ElementId labels. If there are no remaining child elements to traverse, 0 is returned.
Returns
the element id or 0
Implemented in PackedDecode, and XmlDecode.
Referenced by PcodeOpRaw::decode(), RangeList::decode(), AddrSpaceManager::decodeSpace(), AddrSpaceManager::decodeSpaces(), and ContextDatabase::decodeTracked().
virtual bool Decoder::readBool (void) pure virtual
Parse the current attribute as a boolean value.
The last attribute, as returned by getNextAttributeId, is treated as a boolean, and its value is returned.
Returns
the boolean value associated with the current attribute.
Implemented in PackedDecode, and XmlDecode.
Referenced by AddrSpace::decodeBasicAttributes().
virtual bool Decoder::readBool (const AttributeId & attribId) pure virtual
Find and parse a specific attribute in the current element as a boolean value.
The set of attributes for the current element is searched for a match to the given attribute id. This attribute is then parsed as a boolean and its value returned. If there is no attribute matching the id, an exception is thrown. Parsing via getNextAttributeId is reset.
Parameters
attribId is the specific attribute id to match
Returns
the boolean value
Implemented in PackedDecode, and XmlDecode.
virtual intb Decoder::readSignedInteger (void) pure virtual
Parse the current attribute as a signed integer value.
The last attribute, as returned by getNextAttributeId, is treated as a signed integer, and its value is returned.
Returns
the signed integer value associated with the current attribute.
Implemented in PackedDecode, and XmlDecode.
Referenced by PcodeOpRaw::decode(), OverlaySpace::decode(), AddrSpace::decodeAttributes(), AddrSpace::decodeBasicAttributes(), and PcodeEmit::decodeOp().
virtual intb Decoder::readSignedInteger (const AttributeId & attribId) pure virtual
Find and parse a specific attribute in the current element as a signed integer.
The set of attributes for the current element is searched for a match to the given attribute id. This attribute is then parsed as a signed integer and its value returned. If there is no attribute matching the id, an exception is thrown. Parsing via getNextAttributeId is reset.
Parameters
attribId is the specific attribute id to match
Returns
the signed integer value
Implemented in PackedDecode, and XmlDecode.
virtual intb Decoder::readSignedIntegerExpectString (const string & expect, intb expectval) pure virtual
Parse the current attribute as either a signed integer value or a string.
If the attribute is an integer, its value is returned. If the attribute is a string, it must match an expected string passed to the method, and a predetermined integer value associated with the string is returned. If the attribute neither matches the expected string nor is an integer, the return value is undefined.
Parameters
expect is the string value to expect if the attribute is encoded as a string
expectval is the integer value to return if the attribute matches the expected string
Returns
the encoded integer or the integer value associated with the expected string
Implemented in PackedDecode, and XmlDecode.
virtual intb Decoder::readSignedIntegerExpectString (const AttributeId & attribId, const string & expect, intb expectval) pure virtual
Find and parse a specific attribute in the current element as either a signed integer or a string.
If the attribute is an integer, its value is parsed and returned. If the attribute is encoded as a string, it must match an expected string passed to this method. In this case, a predetermined integer value is passed back, indicating a matching string was parsed. If the attribute neither matches the expected string nor is an integer, the return value is undefined. If there is no attribute matching the id, an exception is thrown.
Parameters
attribId is the specific attribute id to match
expect is the string to expect, if the attribute is not encoded as an integer
expectval is the integer value to return if the attribute matches the expected string
Returns
the encoded integer or the integer value associated with the expected string
Implemented in PackedDecode, and XmlDecode.
virtual AddrSpace* Decoder::readSpace (void) pure virtual
Parse the current attribute as an address space.
The last attribute, as returned by getNextAttributeId, is returned as an address space.
Returns
the address space associated with the current attribute.
Implemented in PackedDecode, and XmlDecode.
Referenced by PcodeOpRaw::decode(), SpacebaseSpace::decode(), OverlaySpace::decode(), VarnodeData::decodeFromAttributes(), and Range::decodeFromAttributes().
virtual AddrSpace* Decoder::readSpace (const AttributeId & attribId) pure virtual
Find the specific attribute in the current element and return it as an address space.
Search attributes from the current element for a match to the given attribute id. Return this attribute as an address space. If there is no attribute matching the id, an exception is thrown. Parse via getNextAttributeId is reset.
Parameters
attribId is the specific attribute id to match
Returns
the address space associated with the attribute
Implemented in PackedDecode, and XmlDecode.
virtual string Decoder::readString (void) pure virtual
Parse the current attribute as a string.
The last attribute, as returned by getNextAttributeId, is returned as a string.
Returns
the string associated with the current attribute.
Implemented in PackedDecode, and XmlDecode.
Referenced by TruncationTag::decode(), RangeProperties::decode(), OverlaySpace::decode(), JoinSpace::decodeAttributes(), AddrSpace::decodeBasicAttributes(), ContextInternal::decodeContext(), VarnodeData::decodeFromAttributes(), Range::decodeFromAttributes(), and AddrSpaceManager::decodeSpaces().
virtual string Decoder::readString (const AttributeId & attribId) pure virtual
Find the specific attribute in the current element and return it as a string.
The set of attributes for the current element is searched for a match to the given attribute id. This attribute is then returned as a string. If there is no attribute matching the id, and exception is thrown. Parse via getNextAttributeId is reset.
Parameters
attribId is the specific attribute id to match
Returns
the string associated with the attribute
Implemented in PackedDecode, and XmlDecode.
virtual uintb Decoder::readUnsignedInteger (void) pure virtual
Parse the current attribute as an unsigned integer value.
The last attribute, as returned by getNextAttributeId, is treated as an unsigned integer, and its value is returned.
Returns
the unsigned integer value associated with the current attribute.
Implemented in PackedDecode, and XmlDecode.
Referenced by TrackedContext::decode(), TruncationTag::decode(), SeqNum::decode(), RangeProperties::decode(), AddrSpace::decodeAttributes(), JoinSpace::decodeAttributes(), AddrSpace::decodeBasicAttributes(), ContextInternal::decodeContext(), and Range::decodeFromAttributes().
virtual uintb Decoder::readUnsignedInteger (const AttributeId & attribId) pure virtual
Find and parse a specific attribute in the current element as an unsigned integer.
The set of attributes for the current element is searched for a match to the given attribute id. This attribute is then parsed as an unsigned integer and its value returned. If there is no attribute matching the id, an exception is thrown. Parsing via getNextAttributeId is reset.
Parameters
attribId is the specific attribute id to match
Returns
the unsigned integer value
Implemented in PackedDecode, and XmlDecode.
virtual void Decoder::rewindAttributes (void) pure virtual
Reset attribute traversal for the current element.
Attributes for a single element can be traversed more than once using the getNextAttributeId method.
Implemented in PackedDecode, and XmlDecode.
Referenced by ContextInternal::decode(), and VarnodeData::decodeFromAttributes().
void Decoder::skipElement (void) inline
Skip parsing of the next element.
The element skipped is the one that would be opened by the next call to openElement.
References closeElementSkipping(), and openElement().
The documentation for this class was generated from the following file:
marshal.hh