decompiler: Range Class Reference
Range Class Reference
A contiguous range of bytes in some address space.
#include <address.hh>
Public Member Functions
Range (AddrSpace *s, uintb f, uintb l)
Construct a Range from offsets.
Range (void)
Constructor for use with decode.
Range (const RangeProperties &properties, const AddrSpaceManager *manage)
Construct range out of basic properties.
AddrSpace * getSpace (void) const
Get the address space containing this Range.
uintb getFirst (void) const
Get the offset of the first byte in this Range.
uintb getLast (void) const
Get the offset of the last byte in this Range.
Address getFirstAddr (void) const
Get the address of the first byte.
Address getLastAddr (void) const
Get the address of the last byte.
Address getLastAddrOpen (const AddrSpaceManager *manage) const
Get address of first byte after this.
bool contains (const Address &addr) const
Determine if the address is in this Range.
bool operator< (const Range &op2) const
Sorting operator for Ranges.
void printBounds (ostream &s) const
Print this Range to a stream.
void encode (Encoder &encoder) const
Encode this Range to a stream.
void decode (Decoder &decoder)
Restore this from a stream.
void decodeFromAttributes (Decoder &decoder)
Read from attributes on another tag.
Private Attributes
AddrSpace * spc
Space containing range.
uintb first
Offset of first byte in this Range.
uintb last
Offset of last byte in this Range.
Friends
class RangeList
Detailed Description
A contiguous range of bytes in some address space.
Constructor & Destructor Documentation
Range::Range (AddrSpace * s, uintb f, uintb l) inline
Construct a Range from offsets.
Offsets must expressed in bytes as opposed to addressable words
Parameters
s is the address space containing the range
f is the offset of the first byte in the range
l is the offset of the last byte in the range
References first, last, and spc.
Member Function Documentation
bool Range::contains (const Address & addr) const inline
Determine if the address is in this Range.
Parameters
addr is the Address to test for containment
Returns
true if addr is in this Range
References first, Address::getOffset(), Address::getSpace(), last, and spc.
void Range::decode (Decoder & decoder)
Restore this from a stream.
Reconstruct this object from a <range> or <register> element
Parameters
decoder is the stream decoder
References Decoder::closeElement(), decodeFromAttributes(), and Decoder::openElement().
Referenced by RangeList::decode().
void Range::decodeFromAttributes (Decoder & decoder)
Read from attributes on another tag.
Reconstruct from attributes that may not be part of a <range> element.
Parameters
decoder is the stream decoder
References first, Decoder::getAddrSpaceManager(), AddrSpaceManager::getDefaultCodeSpace(), AddrSpace::getHighest(), Decoder::getNextAttributeId(), Translate::getRegister(), AddrSpace::getTrans(), last, VarnodeData::offset, Decoder::readSpace(), Decoder::readString(), Decoder::readUnsignedInteger(), VarnodeData::size, VarnodeData::space, and spc.
Referenced by decode(), and ContextInternal::decodeFromSpec().
void Range::encode (Encoder & encoder) const
Encode this Range to a stream.
Encode this to a stream as a <range> element.
Parameters
encoder is the stream encoder
References Encoder::closeElement(), first, last, Encoder::openElement(), spc, Encoder::writeSpace(), and Encoder::writeUnsignedInteger().
Address Range::getLastAddrOpen (const AddrSpaceManager * manage) const
Get address of first byte after this.
Get the last address +1, updating the space, or returning the extremal address if necessary
Parameters
manage is used to fetch the next address space
References AddrSpace::getHighest(), AddrSpaceManager::getNextSpaceInOrder(), last, Address::m_maximal, and spc.
Referenced by ContextInternal::decodeFromSpec().
bool Range::operator< (const Range & op2) const inline
Sorting operator for Ranges.
Compare based on address space, then the starting offset
Parameters
op2 is the Range to compare with this
Returns
true if this comes before op2
References first, AddrSpace::getIndex(), and spc.
void Range::printBounds (ostream & s) const
Print this Range to a stream.
Output a description of this Range like: ram: 7f-9c
Parameters
s is the output stream
References first, AddrSpace::getName(), last, and spc.
The documentation for this class was generated from the following files:
address.hh
address.cc