decompiler: PcodeCacher Class Reference
PcodeCacher Class Reference
Class for caching a chunk of p-code, prior to emitting.
#include <sleigh.hh>
Public Member Functions
PcodeCacher (void)
Constructor.
~PcodeCacher (void)
Destructor.
VarnodeData * allocateVarnodes (uint4 size)
Allocate data objects for a new set of Varnodes.
PcodeData * allocateInstruction (void)
Allocate a data object for a new p-code operation.
void addLabelRef (VarnodeData *ptr)
Denote a Varnode holding a relative branch offset.
void addLabel (uint4 id)
Attach a label to the next p-code instruction.
void clear (void)
Reset the cache so that all objects are unallocated.
void resolveRelatives (void)
Rewrite branch target Varnodes as relative offsets.
void emit (const Address &addr, PcodeEmit *emt) const
Pass the cached p-code data to the emitter.
Private Member Functions
VarnodeData * expandPool (uint4 size)
Expand the memory pool.
Private Attributes
VarnodeData * poolstart
Start of the pool of VarnodeData objects.
VarnodeData * curpool
First unused VarnodeData.
VarnodeData * endpool
End of the pool of VarnodeData objects.
vector< PcodeData > issued
P-code ops issued for the current instruction.
list< RelativeRecord > label_refs
References to labels.
vector< uintb > labels
Locations of labels.
Detailed Description
Class for caching a chunk of p-code, prior to emitting.
The engine accumulates PcodeData and VarnodeData objects for a single instruction. Once the full instruction is constructed, the objects are passed to the emitter (PcodeEmit) via the emit() method. The class acts as a pool of memory for PcodeData and VarnodeData objects that can be reused repeatedly to emit multiple instructions.
Member Function Documentation
void PcodeCacher::addLabel (uint4 id)
Attach a label to the next p-code instruction.
The label has an id that is referred to by Varnodes holding intra-instruction branch targets, prior to converting them to a relative branch offset. The label is associated with the absolute index of the next PcodeData object to be issued, facilitating this conversion.
Parameters
id is the given id of the label
References issued, and labels.
void PcodeCacher::addLabelRef (VarnodeData * ptr)
Denote a Varnode holding a relative branch offset.
Store off a reference to the Varnode and the absolute index of the next instruction. The Varnode must be an operand of the current instruction.
Parameters
ptr is the Varnode reference
References issued, and label_refs.
PcodeData* PcodeCacher::allocateInstruction (void) inline
Allocate a data object for a new p-code operation.
Returns
the new PcodeData object
References PcodeData::invar, issued, and PcodeData::outvar.
VarnodeData* PcodeCacher::allocateVarnodes (uint4 size) inline
Allocate data objects for a new set of Varnodes.
Parameters
size is the number of objects to allocate
Returns
a pointer to the array of available VarnodeData objects
References curpool, endpool, and expandPool().
void PcodeCacher::emit (const Address & addr, PcodeEmit * emt) const
Pass the cached p-code data to the emitter.
Each p-code operation is presented to the emitter via its dump() method.
Parameters
addr is the Address associated with the p-code operation
emt is the emitter
References PcodeEmit::dump(), and issued.
Referenced by Sleigh::oneInstruction().
VarnodeData * PcodeCacher::expandPool (uint4 size) private
Expand the memory pool.
Expand the VarnodeData pool so that size more elements fit, and return a pointer to first available element.
Parameters
size is the number of elements to expand the pool by
Returns
the first available VarnodeData
References curpool, endpool, issued, label_refs, and poolstart.
Referenced by allocateVarnodes().
void PcodeCacher::resolveRelatives (void)
Rewrite branch target Varnodes as relative offsets.
Assuming all the PcodeData has been generated for an instruction, go resolve any relative offsets and back patch their value(s) into the PcodeData
References calc_mask(), label_refs, labels, VarnodeData::offset, and VarnodeData::size.
Referenced by Sleigh::oneInstruction().
The documentation for this class was generated from the following files:
sleigh.hh
sleigh.cc