decompiler: OverlaySpace Class Reference
OverlaySpace Class Reference
An overlay space.
#include <space.hh>
Public Member Functions
OverlaySpace (AddrSpaceManager *m, const Translate *t)
Constructor.
virtual AddrSpace * getContain (void) const
Return this space's containing space (if any)
virtual void saveXml (ostream &s) const
Write the details of this space as XML.
virtual void decode (Decoder &decoder)
Recover the details of this space from XML.
Public Member Functions inherited from AddrSpace
AddrSpace (AddrSpaceManager *m, const Translate *t, spacetype tp, const string &nm, uint4 size, uint4 ws, int4 ind, uint4 fl, int4 dl)
AddrSpace (AddrSpaceManager *m, const Translate *t, spacetype tp)
For use with decode.
virtual ~AddrSpace (void)
The address space destructor.
const string & getName (void) const
Get the name.
AddrSpaceManager * getManager (void) const
Get the space manager.
const Translate * getTrans (void) const
Get the processor translator.
spacetype getType (void) const
Get the type of space.
int4 getDelay (void) const
Get number of heritage passes being delayed.
int4 getDeadcodeDelay (void) const
Get number of passes before deadcode removal is allowed.
int4 getIndex (void) const
Get the integer identifier.
uint4 getWordSize (void) const
Get the addressable unit size.
uint4 getAddrSize (void) const
Get the size of the space.
uintb getHighest (void) const
Get the highest byte-scaled address.
uintb getPointerLowerBound (void) const
Get lower bound for assuming an offset is a pointer.
uintb getPointerUpperBound (void) const
Get upper bound for assuming an offset is a pointer.
int4 getMinimumPtrSize (void) const
Get the minimum pointer size for this space.
uintb wrapOffset (uintb off) const
Wrap -off- to the offset that fits into this space.
char getShortcut (void) const
Get the shortcut character.
bool isHeritaged (void) const
Return true if dataflow has been traced.
bool doesDeadcode (void) const
Return true if dead code analysis should be done on this space.
bool hasPhysical (void) const
Return true if data is physically stored in this.
bool isBigEndian (void) const
Return true if values in this space are big endian.
bool isReverseJustified (void) const
Return true if alignment justification does not match endianness.
bool isFormalStackSpace (void) const
Return true if this is attached to the formal stack pointer.
bool isOverlay (void) const
Return true if this is an overlay space.
bool isOverlayBase (void) const
Return true if other spaces overlay this space.
bool isOtherSpace (void) const
Return true if this is the other address space.
bool isTruncated (void) const
Return true if this space is truncated from its original size.
bool hasNearPointers (void) const
Return true if near (truncated) pointers into this space are possible.
void printOffset (ostream &s, uintb offset) const
Write an address offset to a stream.
virtual int4 numSpacebase (void) const
Number of base registers associated with this space.
virtual const VarnodeData & getSpacebase (int4 i) const
Get a base register that creates this virtual space.
virtual const VarnodeData & getSpacebaseFull (int4 i) const
Return original spacebase register before truncation.
virtual bool stackGrowsNegative (void) const
Return true if a stack in this space grows negative.
virtual void encodeAttributes (Encoder &encoder, uintb offset) const
Encode address attributes to a stream.
virtual void encodeAttributes (Encoder &encoder, uintb offset, int4 size) const
Encode an address and size attributes to a stream.
virtual uintb decodeAttributes (Decoder &decoder, uint4 &size) const
Recover an offset and size.
virtual void printRaw (ostream &s, uintb offset) const
Write an address in this space to a stream.
virtual uintb read (const string &s, int4 &size) const
Read in an address (and possible size) from a string.
Private Attributes
AddrSpace * baseSpace
Space being overlayed.
Additional Inherited Members
Public Types inherited from AddrSpace
enum {
big_endian = 1, heritaged = 2, does_deadcode = 4, programspecific = 8,
reverse_justification = 16, formal_stackspace = 0x20, overlay = 0x40, overlaybase = 0x80,
truncated = 0x100, hasphysical = 0x200, is_otherspace = 0x400, has_nearpointers = 0x800
}
Static Public Member Functions inherited from AddrSpace
static uintb addressToByte (uintb val, uint4 ws)
Scale from addressable units to byte units.
static uintb byteToAddress (uintb val, uint4 ws)
Scale from byte units to addressable units.
static int4 addressToByteInt (int4 val, uint4 ws)
Scale int4 from addressable units to byte units.
static int4 byteToAddressInt (int4 val, uint4 ws)
Scale int4 from byte units to addressable units.
static bool compareByIndex (const AddrSpace *a, const AddrSpace *b)
Compare two spaces by their index.
Protected Member Functions inherited from AddrSpace
void calcScaleMask (void)
Calculate scale and mask.
void setFlags (uint4 fl)
Set a cached attribute.
void clearFlags (uint4 fl)
Clear a cached attribute.
void saveBasicAttributes (ostream &s) const
Write the XML attributes of this space.
void decodeBasicAttributes (Decoder &decoder)
Read attributes for this space from an open XML element.
void truncateSpace (uint4 newsize)
Protected Attributes inherited from AddrSpace
string name
Name of this space.
uint4 addressSize
Size of an address into this space in bytes.
uint4 wordsize
Size of unit being addressed (1=byte)
int4 minimumPointerSize
Smallest size of a pointer into this space (in bytes)
int4 index
An integer identifier for the space.
int4 delay
Delay in heritaging this space.
int4 deadcodedelay
Delay before deadcode removal is allowed on this space.
Detailed Description
An overlay space.
A different code and data layout that occupies the same memory as another address space. Some compilers use this concept to increase the logical size of a program without increasing its physical memory requirements. An overlay space allows the same physical location to contain different code and be labeled with different symbols, depending on context. From the point of view of reverse engineering, the different code and symbols are viewed as a logically distinct space.
Constructor & Destructor Documentation
OverlaySpace::OverlaySpace (AddrSpaceManager * m, const Translate * t)
Constructor.
Parameters
m is the address space manager
t is the processor translator
References baseSpace, AddrSpace::overlay, and AddrSpace::setFlags().
Member Function Documentation
virtual AddrSpace* OverlaySpace::getContain (void) const inline virtual
Return this space's containing space (if any)
If this space is virtual, then this routine returns the containing address space, otherwise it returns NULL.
Returns
a pointer to the containing space or NULL
Reimplemented from AddrSpace.
References baseSpace.
void OverlaySpace::saveXml (ostream & s) const virtual
Write the details of this space as XML.
Write a tag fully describing the details of this space suitable for later recovery via decode.
Parameters
s is the stream being written
Reimplemented from AddrSpace.
References a_v(), a_v_i(), baseSpace, AddrSpace::getName(), AddrSpace::index, and AddrSpace::name.
The documentation for this class was generated from the following files:
space.hh
space.cc