decompiler: Encoder Class Reference
Encoder Class Reference abstract
A class for writing structured data to a stream.
#include <marshal.hh>
Public Member Functions
virtual ~Encoder (void)
Destructor.
virtual void openElement (const ElementId &elemId)=0
Begin a new element in the encoding.
virtual void closeElement (const ElementId &elemId)=0
End the current element in the encoding.
virtual void writeBool (const AttributeId &attribId, bool val)=0
Write an annotated boolean value into the encoding.
virtual void writeSignedInteger (const AttributeId &attribId, intb val)=0
Write an annotated signed integer value into the encoding.
virtual void writeUnsignedInteger (const AttributeId &attribId, uintb val)=0
Write an annotated unsigned integer value into the encoding.
virtual void writeString (const AttributeId &attribId, const string &val)=0
Write an annotated string into the encoding.
virtual void writeSpace (const AttributeId &attribId, const AddrSpace *spc)=0
Write an address space reference into the encoding.
Detailed Description
A class for writing structured data to a stream.
The resulting encoded data is structured similarly to an XML document. The document contains a nested set of elements, with labels corresponding to the ElementId class. A single element can hold zero or more attributes and zero or more child elements. An attribute holds a primitive data element (bool, integer, string) and is labeled by an AttributeId. The document is written using a sequence of openElement() and closeElement() calls, intermixed with write*() calls to encode the data primitives. All primitives written using a write*() call are associated with current open element, and all write*() calls for one element must come before opening any child element. The traditional XML element text content can be written using the special ATTRIB_CONTENT AttributeId, which must be the last write*() call associated with the specific element.
Member Function Documentation
virtual void Encoder::closeElement (const ElementId & elemId) pure virtual
End the current element in the encoding.
The current element must match the given annotation or an exception is thrown.
Parameters
elemId is the given (expected) annotation for the current element
Implemented in PackedEncode, and XmlEncode.
Referenced by TrackedContext::encode(), Address::encode(), SeqNum::encode(), Range::encode(), RangeList::encode(), ContextInternal::encode(), ContextInternal::encodeContext(), and ContextDatabase::encodeTracked().
virtual void Encoder::openElement (const ElementId & elemId) pure virtual
Begin a new element in the encoding.
The element will have the given ElementId annotation and becomes the current element.
Parameters
elemId is the given ElementId annotation
Implemented in PackedEncode, and XmlEncode.
Referenced by TrackedContext::encode(), Address::encode(), SeqNum::encode(), Range::encode(), RangeList::encode(), ContextInternal::encode(), ContextInternal::encodeContext(), and ContextDatabase::encodeTracked().
virtual void Encoder::writeBool (const AttributeId & attribId, bool val) pure virtual
Write an annotated boolean value into the encoding.
The boolean data is associated with the given AttributeId annotation and the current open element.
Parameters
attribId is the given AttributeId annotation
val is boolean value to encode
Implemented in PackedEncode, and XmlEncode.
virtual void Encoder::writeSignedInteger (const AttributeId & attribId, intb val) pure virtual
Write an annotated signed integer value into the encoding.
The integer is associated with the given AttributeId annotation and the current open element.
Parameters
attribId is the given AttributeId annotation
val is the signed integer value to encode
Implemented in PackedEncode, and XmlEncode.
Referenced by AddrSpace::encodeAttributes().
virtual void Encoder::writeSpace (const AttributeId & attribId, const AddrSpace * spc) pure virtual
Write an address space reference into the encoding.
The address space is associated with the given AttributeId annotation and the current open element.
Parameters
attribId is the given AttributeId annotation
spc is the address space to encode
Implemented in PackedEncode, and XmlEncode.
Referenced by Range::encode(), AddrSpace::encodeAttributes(), and JoinSpace::encodeAttributes().
virtual void Encoder::writeString (const AttributeId & attribId, const string & val) pure virtual
Write an annotated string into the encoding.
The string is associated with the given AttributeId annotation and the current open element.
Parameters
attribId is the given AttributeId annotation
val is the string to encode
Implemented in PackedEncode, and XmlEncode.
Referenced by JoinSpace::encodeAttributes(), and ContextInternal::encodeContext().
virtual void Encoder::writeUnsignedInteger (const AttributeId & attribId, uintb val) pure virtual
Write an annotated unsigned integer value into the encoding.
The integer is associated with the given AttributeId annotation and the current open element.
Parameters
attribId is the given AttributeId annotation
val is the unsigned integer value to encode
Implemented in PackedEncode, and XmlEncode.
Referenced by TrackedContext::encode(), SeqNum::encode(), Range::encode(), AddrSpace::encodeAttributes(), JoinSpace::encodeAttributes(), and ContextInternal::encodeContext().
The documentation for this class was generated from the following file:
marshal.hh