decompiler: TrackedContext Struct Reference
TrackedContext Struct Reference
A tracked register (Varnode) and the value it contains.
#include <globalcontext.hh>
Public Member Functions
void decode (Decoder &decoder)
Decode this from a stream.
void encode (Encoder &encoder) const
Encode this to a stream.
Public Attributes
VarnodeData loc
Storage details of the register being tracked.
uintb val
The value of the register.
Detailed Description
A tracked register (Varnode) and the value it contains.
This is the object returned when querying for tracked registers, via ContextDatabase::getTrackedSet(). It holds the storage details of the register and the actual value it holds at the point of the query.
Member Function Documentation
void TrackedContext::decode (Decoder & decoder)
Decode this from a stream.
Parse a <set> element to fill in the storage and value details.
Parameters
decoder is the stream decoder
References Decoder::closeElement(), VarnodeData::decodeFromAttributes(), loc, Decoder::openElement(), Decoder::readUnsignedInteger(), and val.
void TrackedContext::encode (Encoder & encoder) const
Encode this to a stream.
The register storage and value are encoded as a <set> element.
Parameters
encoder is the stream encoder
References Encoder::closeElement(), AddrSpace::encodeAttributes(), loc, VarnodeData::offset, Encoder::openElement(), VarnodeData::size, VarnodeData::space, val, and Encoder::writeUnsignedInteger().
The documentation for this struct was generated from the following files:
globalcontext.hh
globalcontext.cc