decompiler: VarnodeData Struct Reference
VarnodeData Struct Reference
Data defining a specific memory location.
#include <pcoderaw.hh>
Public Member Functions
bool operator< (const VarnodeData &op2) const
An ordering for VarnodeData.
bool operator== (const VarnodeData &op2) const
Compare for equality.
bool operator!= (const VarnodeData &op2) const
Compare for inequality.
Address getAddr (void) const
Get the location of the varnode as an address.
AddrSpace * getSpaceFromConst (void) const
Treat this as a constant and recover encoded address space.
void decode (Decoder &decoder)
Recover this object from a stream.
void decodeFromAttributes (Decoder &decoder)
Recover this object from attributes of the current open element.
bool contains (const VarnodeData &op2) const
Does this container another given VarnodeData.
Public Attributes
AddrSpace * space
The address space.
uintb offset
The offset within the space.
uint4 size
The number of bytes in the location.
Detailed Description
Data defining a specific memory location.
Within the decompiler's model of a processor, any register, memory location, or other variable can always be represented as an address space, an offset within the space, and the size of the sequence of bytes. This is more commonly referred to as a Varnode, but this is a bare-bones container for the data that doesn't have the cached attributes and the dataflow links of the Varnode within its syntax tree.
Member Function Documentation
bool VarnodeData::contains (const VarnodeData & op2) const
Does this container another given VarnodeData.
Return true, if this, as an address range, contains the other address range
Parameters
op2 is the other VarnodeData to test for containment
Returns
true if this contains the other
References offset, size, and space.
void VarnodeData::decode (Decoder & decoder)
Recover this object from a stream.
Build this VarnodeData from an <addr>, <register>, or <varnode> element.
Parameters
decoder is the stream decoder
References Decoder::closeElement(), decodeFromAttributes(), and Decoder::openElement().
Referenced by Address::decode(), and PcodeOpRaw::decode().
void VarnodeData::decodeFromAttributes (Decoder & decoder)
Recover this object from attributes of the current open element.
Collect attributes for the VarnodeData possibly from amidst other attributes
Parameters
decoder is the stream decoder
References AddrSpace::decodeAttributes(), Decoder::getAddrSpaceManager(), AddrSpaceManager::getDefaultCodeSpace(), Decoder::getNextAttributeId(), Translate::getRegister(), AddrSpace::getTrans(), offset, Decoder::readSpace(), Decoder::readString(), Decoder::rewindAttributes(), size, and space.
Referenced by decode(), TrackedContext::decode(), and ContextInternal::decode().
Address VarnodeData::getAddr (void) const inline
Get the location of the varnode as an address.
This is a convenience function to construct a full Address from the VarnodeData's address space and offset
Returns
the address of the varnode
References offset, and space.
Referenced by AddrSpaceManager::constructFloatExtensionAddress(), AddrSpaceManager::constructJoinAddress(), ContextInternal::decode(), EmulateMemory::executeBranch(), EmulatePcodeCache::executeBranch(), and EmulateMemory::executeCall().
AddrSpace * VarnodeData::getSpaceFromConst (void) const inline
Treat this as a constant and recover encoded address space.
Returns
the encoded AddrSpace
References offset.
Referenced by EmulateMemory::executeLoad(), and EmulateMemory::executeStore().
bool VarnodeData::operator!= (const VarnodeData & op2) const inline
Compare for inequality.
Compare VarnodeData for inequality. If either the space, offset, or size is not equal, return true.
Parameters
op2 is the object being compared to
Returns
true if this is not equal to op2
References offset, size, and space.
bool VarnodeData::operator< (const VarnodeData & op2) const inline
An ordering for VarnodeData.
VarnodeData can be sorted in terms of the space its in (the space's index), the offset within the space, and finally by the size.
Parameters
op2 is the object being compared to
Returns
true if this is less than op2
References AddrSpace::getIndex(), offset, size, and space.
bool VarnodeData::operator== (const VarnodeData & op2) const inline
Compare for equality.
Compare VarnodeData for equality. The space, offset, and size must all be exactly equal
Parameters
op2 is the object being compared to
Returns
true if this is equal to op2
References offset, size, and space.
The documentation for this struct was generated from the following files:
pcoderaw.hh
pcoderaw.cc